// nuxt-app/pages/components/toast.vue
<template>
    <div>
      <pie-toast 
      message="This is a message"
      isDismissible></pie-toast>
    </div>
  </template>
  
  <script setup lang="ts">
  import { definePageMeta } from '#imports';
  import '@justeattakeaway/pie-webc/components/toast.js';
  
  definePageMeta({
    title: 'Toast',
  });
  </script>

// nextjs-app-v14/src/app/components/toast/toast.tsx
'use client';

import NavigationLayout from "@/app/layout/navigation";
import { PieToast } from '@justeattakeaway/pie-webc/react/toast.js';

export default function Toast() {

    return (
        <NavigationLayout title="Toast">
            <PieToast message="This is a message" isDismissible />
        </NavigationLayout>
    );
}
