// nuxt-app/pages/components/cookie-banner.vue
<template>
  <div>
    <pie-cookie-banner hasPrimaryActionsOnly :locale="daDK" cookieTechnologiesLink="https://justeattakeaway.com"
      cookieStatementLink="https://justeattakeaway.com">
    </pie-cookie-banner>
  </div>
</template>

<script setup lang="ts">
import { definePageMeta } from '#imports';
import '@justeattakeaway/pie-webc/components/cookie-banner.js';

definePageMeta({
    title: 'Cookie Banner',
});

// TODO: DSW-1710 - Update this to use the TS declaration for locales.
// Currently importing the JSON file directly as a workaround as Nuxt wants import assertions.
import daDK from '@justeattakeaway/pie-cookie-banner/locales/da-dk.json';
</script>

// nextjs-app-v14/src/app/components/cookie-banner/page.tsx
'use client';

import NavigationLayout from "@/layout/navigation";
import { PieCookieBanner } from '@justeattakeaway/pie-webc/react/cookie-banner.js';
// TODO: Remove this comment as soon as we provide the TS declaration for locales
// @ts-ignore: missing declaration for locales
import daDK from '@justeattakeaway/pie-cookie-banner/locales/dk-dk.json';

export default function CookieBanner() {
    return (
        <NavigationLayout title="Cookie Banner">
        <PieCookieBanner
            defaultPreferences={{functional: true, personalized: true, analytical: true}}
            locale={daDK}
            hasPrimaryActionsOnly
            cookieTechnologiesLink="https://justeattakeaway.com"
            cookieStatementLink="https://justeattakeaway.com" />
        </NavigationLayout>
    );
}
