// nuxt-app/pages/components/data-table.vue
<template>
    <div>
        <h2>PIE Data Table – Table with no header</h2>
        <pie-data-table
            :columns="sampleColumns"
            :data="sampleData"
            data-test-id="pie-data-table"
        ></pie-data-table>

        <pie-divider></pie-divider>

        <pie-data-table
            :columns="sampleColumns"
            :data="sampleData"
            data-test-id="PieDataTable">
            <pie-data-table-header slot="table-header" heading="PIE Data Table – Table with header" subHeading="Optional subtitle text">
                <pie-button slot="action-button" variant="secondary" size="xsmall">Action</pie-button>
                <pie-button slot="action-button" variant="secondary" size="xsmall">Action</pie-button>
                <pie-button slot="action-button" variant="secondary" size="xsmall">Action</pie-button>
            </pie-data-table-header>
        </pie-data-table>
    </div>
</template>

<script setup lang="ts">
import { definePageMeta } from '#imports';
import '@justeattakeaway/pie-webc/components/data-table.js';
import '@justeattakeaway/pie-webc/components/data-table-header.js';
import '@justeattakeaway/pie-webc/components/button.js';
import '@justeattakeaway/pie-webc/components/divider.js';
import { sampleColumns, sampleData } from '../../data/sampleTableData';

definePageMeta({
    title: 'DataTable',
});
</script>

// nextjs-app-v15/src/app/components/data-table/data-table.tsx
'use client';

import NavigationLayout from "@/app/layout/navigation";
import { PieDataTable } from '@justeattakeaway/pie-webc/react/data-table.js';
import { PieDataTableHeader } from '@justeattakeaway/pie-webc/react/data-table-header.js';
import { PieButton } from '@justeattakeaway/pie-webc/react/button.js';
import { PieDivider } from '@justeattakeaway/pie-webc/react/divider.js';
import { sampleColumns, sampleData } from './sample-table-data';

export default function DataTable() {
    return (
        <NavigationLayout title="DataTable">
            <h2>PIE Data Table – Table with no header</h2>
            <PieDataTable columns={sampleColumns} data={sampleData}
                data-test-id="PieDataTable"
            ></PieDataTable>

            <PieDivider />

            <PieDataTable columns={sampleColumns} data={sampleData}
                data-test-id="PieDataTable"
            >
                <PieDataTableHeader slot="table-header" heading="PIE Data Table – Table with header"
                    subHeading="Optional subtitle text"
                >
                    <PieButton slot="action-button" variant="secondary" size="xsmall">Action</PieButton>
                    <PieButton slot="action-button" variant="secondary" size="xsmall">Action</PieButton>
                    <PieButton slot="action-button" variant="secondary" size="xsmall">Action</PieButton>
                </PieDataTableHeader>
            </PieDataTable>

        </NavigationLayout>
    );
}
