// nuxt-app/pages/components/breadcrumb.vue
<template>
	<pie-breadcrumb>
		<pie-breadcrumb-item href="/">Home</pie-breadcrumb-item>
		<pie-breadcrumb-item href="#">Breadcrumb</pie-breadcrumb-item>
	</pie-breadcrumb>
</template>

<script setup lang="ts">
import { definePageMeta } from '#imports';
import '@justeattakeaway/pie-webc/components/breadcrumb.js';
import '@justeattakeaway/pie-webc/components/breadcrumb-item.js';

definePageMeta({
    title: 'Breadcrumb',
});
</script>

// nextjs-app-v14/src/app/components/breadcrumb/breadcrumb.tsx
'use client';

import NavigationLayout from "@/app/layout/navigation";
import { PieBreadcrumb } from '@justeattakeaway/pie-webc/react/breadcrumb.js';
import { PieBreadcrumbItem } from '@justeattakeaway/pie-webc/react/breadcrumb-item.js';
import NextLink from 'next/link'

export default function Breadcrumb() {
    return (
        <NavigationLayout title="Breadcrumb">
            <PieBreadcrumb>
                <NextLink passHref href="/" legacyBehavior>
                    <PieBreadcrumbItem href="/">Home</PieBreadcrumbItem>
                </NextLink>
                <PieBreadcrumbItem href="#">Breadcrumb</PieBreadcrumbItem>
            </PieBreadcrumb>
        </NavigationLayout>
    );
}
