// nuxt-app/pages/components/checkbox.vue
<template>
  <div>
    <pie-checkbox :checked="checked" @change="handleCheckboxChange">
      {{ `checked: ${checked}` }}
    </pie-checkbox>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { definePageMeta } from '#imports';
import '@justeattakeaway/pie-webc/components/checkbox.js';

definePageMeta({
    title: 'Checkbox',
});

let checked = ref(false);

function handleCheckboxChange() {
  checked.value = !checked.value;
}

</script>

// nextjs-app-v13/src/pages/components/checkbox.tsx
import NavigationLayout from "@/layout/navigation";
import { PieCheckbox } from "@justeattakeaway/pie-webc/react/checkbox.js";
import { useState } from "react";

export default function Checkbox() {
    const [isCheckboxChecked, setIsCheckboxCheck] = useState(false)

    const handleCheckboxChange = () => {
        setIsCheckboxCheck(current => !current);
    };

    return (
        <NavigationLayout title="Checkbox">
            <PieCheckbox
                checked={isCheckboxChecked}
                onChange={handleCheckboxChange}>
                {`checked: ${isCheckboxChecked}`}
            </PieCheckbox>
        </NavigationLayout>
    );
}
