// nuxt-app/pages/components/chip.vue
<template>
  <div>
    <pie-chip>PIE Chip Default</pie-chip>

    <pie-divider></pie-divider>
    <pie-chip variant="outline">PIE Chip Outline</pie-chip>

    <pie-divider></pie-divider>
    <pie-chip variant="ghost">PIE Chip Ghost</pie-chip>
  </div>
</template>

<script setup lang="ts">
import { definePageMeta } from '#imports';
import '@justeattakeaway/pie-webc/components/chip.js';

definePageMeta({
    title: 'PIE Chip',
});
</script>

// nextjs-app-v13/src/pages/components/chip.tsx
import NavigationLayout from "@/layout/navigation";
import { PieChip } from '@justeattakeaway/pie-webc/react/chip.js';
import { PieDivider } from '@justeattakeaway/pie-webc/react/divider.js';

export default function Chip() {
    return (
        <NavigationLayout title="Chip">
        <PieChip>PIE Chip</PieChip>
        <PieDivider/>
        <PieChip variant="outline">PIE Chip</PieChip>
        <PieDivider/>
        <PieChip variant="ghost">PIE Chip</PieChip>
        </NavigationLayout>
    );
}
