// nuxt-app/pages/components/lottie-player.vue
<template>
  <div>
    <pie-button size="xsmall" @click="handleLoadAnimationClick">
      load another animation
    </pie-button>
    <pie-lottie-player 
      :animationSrc="animationPath"
      :autoPlayDisabled="autoPlayDisabled"
    ></pie-lottie-player>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { definePageMeta } from '#imports';
import '@justeattakeaway/pie-webc/components/button.js';
import '@justeattakeaway/pie-webc/components/lottie-player.js';

const animations = [
    "/animations/preparing.json",
    "/animations/courier.json",
    "/animations/order-confirmed.json",
]

definePageMeta({
    title: 'PIE Lottie Player',
});

let animationIndex = ref(0);
let animationPath = ref(animations[animationIndex.value % animations.length]);
const autoPlayDisabled = ref(false);

function handleLoadAnimationClick () {
  animationIndex.value++;
  animationPath.value = animations[animationIndex.value % animations.length];
}

onMounted(() => {
  const isRunningInPercy = document && document?.location?.search.indexOf('PERCY=true') > -1
  autoPlayDisabled.value = isRunningInPercy ? true : undefined;
});

</script>

// nextjs-app-v13/src/pages/components/lottie-player.tsx
import NavigationLayout from "@/layout/navigation";
import { PieLottiePlayer } from '@justeattakeaway/pie-webc/react/lottie-player.js';
import { PieButton } from '@justeattakeaway/pie-webc/react/button.js';
import { useState } from "react";
import { isServer } from 'lit';

const animations = [
    "/animations/preparing.json",
    "/animations/courier.json",
    "/animations/order-confirmed.json",
]

export default function Page() {
    const [animationIndex, setAnimationIndex] = useState(0);

    function handleLoadAnimationClick() {
        setAnimationIndex(animationIndex + 1);
    }

    const animationPath = animations[animationIndex% animations.length];

    const isRunningInPercy = isServer ? false : document.location.search.indexOf('PERCY=true') > -1;

    return (
        <NavigationLayout title="Lottie Player">
            <div>
                <PieButton size="xsmall" onClick={handleLoadAnimationClick}>load another animation</PieButton>
            </div>
            <PieLottiePlayer animationSrc={animationPath} autoPlayDisabled={isRunningInPercy} />
        </NavigationLayout>
    );
}
