// nuxt-app/pages/components/modal.vue
<template>
  <div>
    <pie-button @click="openModal">Open Modal</pie-button>
    <pie-modal
        heading="Modal Header"
        hasBackButton
        isDismissible
        :isOpen="open"
        :leadingAction="{
          text: 'Confirm'
        }"
        :supportingAction="{
          text: 'Cancel'
        }"
        @pie-modal-close="handleModalClose"
        @pie-modal-back="handleModalClose"
    >
      <p>Modal content</p>
    </pie-modal>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { definePageMeta } from '#imports';
import '@justeattakeaway/pie-webc/components/button.js';
import '@justeattakeaway/pie-webc/components/modal.js';

definePageMeta({
    title: 'Modal',
});

let open = ref(true);

function openModal() {
  open.value = true;
}

function handleModalClose() {
  open.value = false;
}

</script>

// nextjs-app-v13/src/pages/components/modal.tsx
import NavigationLayout from "@/layout/navigation";
import { PieButton } from '@justeattakeaway/pie-webc/react/button.js';
import { PieModal } from '@justeattakeaway/pie-webc/react/modal.js';
import { useState } from "react";

export default function Modal() {
    const [isModalOpen, setIsModalOpen] = useState(true);

    return (
        <NavigationLayout title="Modal">
        <PieButton onClick={() => setIsModalOpen(true)}>Open Modal</PieButton>
        <PieModal
            isOpen={isModalOpen}
            heading="Modal Header"
            isDismissible
            hasBackButton
            leadingAction={{ text: 'Confirm' }}
            supportingAction={{ text: 'Cancel' }}
            onPieModalClose={() => setIsModalOpen(false)}
            onPieModalBack={() => setIsModalOpen(false)}
        >
            <p>Modal content</p>
        </PieModal>
        </NavigationLayout>
    );
}
