// nuxt-app/pages/components/notification.vue
<template>
  <div>
    <pie-button @click="handleToggleNotification">{{ !isNotificationOpen ? 'Open' : 'Close' }} Notification</pie-button>

    <pie-divider/>

    <pie-notification
        variant="info"
        heading="Title"
        :isOpen="isNotificationOpen ? isNotificationOpen : undefined"
        @pie-notification-close="handleCloseNotification"
        @pie-notification-open="handleOpenNotification"
        @pie-notification-leading-action-click="handleCloseNotification"
        @pie-notification-supporting-action-click="handleCloseNotification"
    >
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sit amet tincidunt est, vitae vulputate turpis. Cras pretium venenatis elementum. Duis tristique neque non varius tempor. In hac habitasse platea dictumst. Aenean accumsan vehicula urna.
    </pie-notification>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { definePageMeta } from '#imports';
import '@justeattakeaway/pie-webc/components/button.js';
import '@justeattakeaway/pie-webc/components/divider.js';
import '@justeattakeaway/pie-webc/components/notification.js';

definePageMeta({
  title: 'PIE Notification',
});

let isNotificationOpen = ref(true);

const handleToggleNotification = () =>  {
  isNotificationOpen.value = !isNotificationOpen.value;
}

const handleCloseNotification = () =>  {
  isNotificationOpen.value = false;
}

const handleOpenNotification = () =>  {
  isNotificationOpen.value = true;
}

const leadingAction = {
  text: 'Confirm',
  ariaLabel: 'Descriptive confirmation text',
};

const supportingAction = {
  text: 'Cancel',
  ariaLabel: 'Descriptive cancellation text',
};

</script>

// nextjs-app-v13/src/pages/components/notification.tsx
import { useState } from "react";
import { PieButton } from '@justeattakeaway/pie-webc/react/button.js';
import { PieNotification } from '@justeattakeaway/pie-webc/react/notification.js';
import { PieDivider } from '@justeattakeaway/pie-webc/react/divider.js';
import NavigationLayout from "@/layout/navigation";

export default function Notification() {
  const [isNotificationOpen, setIsNotificationOpen] = useState(true);

  const toggleNotification = () => {
    setIsNotificationOpen((previousState => !previousState))
  }

  return (
    <NavigationLayout title="Notification">
      <PieButton onClick={toggleNotification}>{!isNotificationOpen ? 'Open' : 'Close'} Notification</PieButton>

      <PieDivider />

      <PieNotification
        isOpen={isNotificationOpen}
        variant="info"
        heading="Title"
        leadingAction={{
            text: 'Confirm',
            ariaLabel: 'Descriptive confirmation text',
        }}
        supportingAction={{
            text: 'Cancel',
            ariaLabel: 'Descriptive cancellation text',
        }}
        onPieNotificationClose={() => setIsNotificationOpen(false)}
        onPieNotificationOpen={() => setIsNotificationOpen(true)}
        onPieNotificationLeadingActionClick={() => setIsNotificationOpen(false)}
        onPieNotificationSupportingActionClick={() => setIsNotificationOpen(false)}
      >
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sit amet tincidunt est, vitae vulputate turpis. Cras pretium venenatis elementum. Duis tristique neque non varius tempor. In hac habitasse platea dictumst. Aenean accumsan vehicula urna.
      </PieNotification>
    </NavigationLayout>

  )
}
