// nuxt-app/pages/components/textarea.vue
<template>
  <div>
    <pie-textarea value="foo"></pie-textarea>
    <pie-divider></pie-divider>
    <pie-textarea resize="manual" value="foo"></pie-textarea>
  </div>
</template>

<script setup lang="ts">
import { definePageMeta } from '#imports';
import '@justeattakeaway/pie-webc/components/textarea.js';
import '@justeattakeaway/pie-webc/components/divider.js';

definePageMeta({
  title: 'Textarea',
});
</script>

// nextjs-app-v13/src/pages/components/textarea.tsx
import NavigationLayout from "@/layout/navigation";
import { PieTextarea } from '@justeattakeaway/pie-webc/react/textarea.js';
import { PieDivider } from '@justeattakeaway/pie-webc/react/divider.js';

export default function Textarea() {

    return (
        <NavigationLayout title="Textarea">
            <PieTextarea value="foo"/>

            <PieDivider />

            <PieTextarea
                value="foo"
                resize="manual"
            />
        </NavigationLayout>
    );
}
