// nuxt-app/pages/components/checkbox.vue
<template>
  <div>
    <pie-checkbox :label="`checked: ${checked}`" :checked="checked" @change="handleCheckboxChange">
    </pie-checkbox>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { definePageMeta } from '#imports';
import '@justeattakeaway/pie-checkbox';

definePageMeta({
    title: 'PIE Checkbox',
});

let checked = ref(false);

function handleCheckboxChange() {
  checked.value = !checked.value;
}

</script>

// nextjs-app-v14/src/app/components/checkbox/page.tsx
'use client';

import NavigationLayout from "@/layout/navigation";
import { PieCheckbox } from "@justeattakeaway/pie-webc/react/checkbox.js";
import { useState } from "react";

export default function Checkbox() {
    const [isCheckboxChecked, setIsCheckboxCheck] = useState(false)

    const handleCheckboxChange = () => {
        setIsCheckboxCheck(current => !current);
    };

    return (
        <NavigationLayout title="Checkbox">
            <PieCheckbox
                label={`checked: ${isCheckboxChecked}`}
                checked={isCheckboxChecked}
                onChange={handleCheckboxChange}>
            </PieCheckbox>
        </NavigationLayout>
    );
}
