// nuxt-app/pages/index.vue
<template>
	<div>
		<h3>Demo Integrations</h3>
		<ul>
			<li><pie-link href="/integrations/form">Form Demo</pie-link></li>
		</ul>
		<h3>Component Pages</h3>
		<ul>
			<li><pie-link href="/components/assistive-text">Assistive Text</pie-link></li>
			<li><pie-link href="/components/button">Button</pie-link></li>
			<li><pie-link href="/components/card">Card</pie-link></li>
      <li><pie-link href="/components/checkbox">Checkbox</pie-link></li>
      <li><pie-link href="/components/checkbox-group">Checkbox Group</pie-link></li>
      <li><pie-link href="/components/chip">Chip</pie-link></li>
      <li><pie-link href="/components/cookie-banner">Cookie Banner</pie-link></li>
      <li><pie-link href="/components/form-label">Form Label</pie-link></li>
      <li><pie-link href="/components/icon">Icon</pie-link></li>
      <li><pie-link href="/components/icon-button">Icon Button</pie-link></li>
      <li><pie-link href="/components/lottie-player">Lottie Player</pie-link></li>
      <li><pie-link href="/components/link">Link</pie-link></li>
      <li><pie-link href="/components/modal">Modal</pie-link></li>
      <li><pie-link href="/components/notification">Notification</pie-link></li>
      <li><pie-link href="/components/radio">Radio</pie-link></li>
      <li><pie-link href="/components/spinner">Spinner</pie-link></li>
      <li><pie-link href="/components/switch">Switch</pie-link></li>
      <li><pie-link href="/components/tag">Tag</pie-link></li>
      <li><pie-link href="/components/text-input">Text Input</pie-link></li>
      <li><pie-link href="/components/textarea">Textarea</pie-link></li>
		</ul>
	</div>
</template>

<script setup lang="ts">
import { definePageMeta } from '#imports';

definePageMeta({
    title: 'Aperture',
});

</script>

<style>
ul {
	list-style-type: none;
}
</style>

// nextjs-app-v13/src/pages/index.tsx
import NavigationLayout from "@/layout/navigation";
import { PieLink } from '@justeattakeaway/pie-webc/react/link.js';
import { useRouter } from 'next/router';

export default function Home() {

  const router = useRouter();

  return (
    <NavigationLayout title="Aperture">
    <h2>Demo Integrations</h2>
    <ul>
      <li><PieLink onClick={() => router.push('/integrations/form')} tag="button">Form Demo</PieLink></li>
    </ul>
    <h2>Component Pages</h2>
    <ul>
    <li><PieLink onClick={() => router.push('/components/assistive-text')} tag="button">Assistive Text</PieLink></li>
    <li><PieLink onClick={() => router.push('/components/button')} tag="button">Button</PieLink></li>
    <li><PieLink onClick={() => router.push('/components/card')} tag="button">Card</PieLink></li>
      <li><PieLink onClick={() => router.push('/components/checkbox')} tag="button">Checkbox</PieLink></li>
      <li><PieLink onClick={() => router.push('/components/checkbox-group')} tag="button">Checkbox Group</PieLink></li>
      <li><PieLink onClick={() => router.push('/components/chip')} tag="button">Chip</PieLink></li>
      <li><PieLink onClick={() => router.push('/components/cookie-banner')} tag="button">Cookie Banner</PieLink></li>
      <li><PieLink onClick={() => router.push('/components/form-label')} tag="button">Form Label</PieLink></li>
      <li><PieLink onClick={() => router.push('/components/icon')} tag="button">Icon</PieLink></li>
      <li><PieLink onClick={() => router.push('/components/icon-button')} tag="button">Icon Button</PieLink></li>
      <li><PieLink onClick={() => router.push('/components/link')} tag="button">Link</PieLink></li>
      <li><PieLink onClick={() => router.push('/components/lottie-player')} tag="button">Lottie Player</PieLink></li>
      <li><PieLink onClick={() => router.push('/components/modal')} tag="button">Modal</PieLink></li>
      <li><PieLink onClick={() => router.push('/components/notification')} tag="button">Notification</PieLink></li>
      <li><PieLink onClick={() => router.push('/components/radio')} tag="button">Radio</PieLink></li>
      <li><PieLink onClick={() => router.push('/components/spinner')} tag="button">Spinner</PieLink></li>
      <li><PieLink onClick={() => router.push('/components/switch')} tag="button">Switch</PieLink></li>
      <li><PieLink onClick={() => router.push('/components/tag')} tag="button">Tag</PieLink></li>
      <li><PieLink onClick={() => router.push('/components/text-input')} tag="button">Text Input</PieLink></li>
      <li><PieLink onClick={() => router.push('/components/textarea')} tag="button">Textarea</PieLink></li>
    </ul>
    </NavigationLayout>
  );
}
