// nuxt-app/pages/components/tag.vue
<template>
  <div>
    <h2>Default</h2>
    <div class="c-tag-container">
      <pie-tag
        v-for="variant in variants"
        :key="variant"
        :variant="variant">
        {{ variant }}
      </pie-tag>

      <pie-tag
        v-for="variant in variants"
        :key="variant"
        :variant="variant"
        hasLeadingIcon>
        <icon-fingerprint slot="icon"></icon-fingerprint>
        {{ variant }}
      </pie-tag>

      <pie-tag
        v-for="variant in variants"
        :key="variant"
        :variant="variant"
        isIconOnly>
        <icon-fingerprint slot="icon"></icon-fingerprint>
      </pie-tag>
    </div>

    <h2>Strong</h2>

    <div class="c-tag-container">
      <pie-tag
        v-for="variant in variants"
        :key="variant"
        isStrong
        :variant="variant">
        {{ variant }}
      </pie-tag>
      
      <pie-tag
        v-for="variant in variants"
        :key="variant"
        isStrong
        :variant="variant"
        hasLeadingIcon>
        <icon-fingerprint slot="icon"></icon-fingerprint>
        {{ variant }}
      </pie-tag>

      <pie-tag
        v-for="variant in variants"
        :key="variant"
        isStrong
        :variant="variant"
        isIconOnly>
        <icon-fingerprint slot="icon"></icon-fingerprint>
      </pie-tag>
    </div>
  </div>
</template>

<script setup lang="ts">
import { definePageMeta } from '#imports';
import '@justeattakeaway/pie-webc/components/tag.js';
import { variants } from '@justeattakeaway/pie-webc/components/tag.js';
import '@justeattakeaway/pie-icons-webc/dist/IconFingerprint.js';

import '@justeattakeaway/pie-webc/components/divider.js';

definePageMeta({
    title: 'Tag',
});
</script>

<style>
.c-tag-container {
  display: flex;
  flex-wrap: wrap;
  gap: var(--dt-spacing-b);
}
</style>

// nextjs-app-v15/src/app/components/tag/tag.tsx
'use client';

import NavigationLayout from "@/app/layout/navigation";
import { PieTag, variants } from '@justeattakeaway/pie-webc/react/tag.js';
import { IconFingerprint } from "@justeattakeaway/pie-icons-webc/dist/react/IconFingerprint.js";
import '@/styles/tag.scss';

export default function Tag() {
    return (
        <NavigationLayout title="Tag">
            <h2>Default</h2>
            <div className="c-tag-container">
                {variants.map((variant) => (
                    <PieTag
                        key={variant}
                        variant={variant}
                        hasLeadingIcon>
                        <IconFingerprint slot="icon" />
                        {variant}
                    </PieTag>
                ))}

                {variants.map((variant) => (
                    <PieTag
                        key={variant}
                        variant={variant}
                        isIconOnly>
                        <IconFingerprint slot="icon" />
                    </PieTag>
                ))}

                {variants.map((variant) => (
                    <PieTag
                        key={variant}
                        variant={variant}>
                        {variant}
                    </PieTag>
                ))}
            </div>

            <h2>Strong</h2>

            <div className="c-tag-container">
                {variants.map((variant) => (
                    <PieTag
                        key={variant}
                        variant={variant}
                        isStrong>
                        {variant}
                    </PieTag>
                ))}

                {variants.map((variant) => (
                    <PieTag
                        key={variant}
                        variant={variant}
                        isStrong
                        hasLeadingIcon>
                        <IconFingerprint slot="icon" />
                        {variant}
                    </PieTag>
                ))}

                {variants.map((variant) => (
                    <PieTag
                        key={variant}
                        variant={variant}
                        isIconOnly>
                        <IconFingerprint slot="icon" />
                    </PieTag>
                ))}
            </div>
        </NavigationLayout>
    );
}
