// nuxt-app/pages/integrations/form.vue
<template>
    <div>
        <form class="form" id="testForm" @submit.prevent="handleSubmit">
            <pie-form-label for="username">
                Username:
            </pie-form-label>
            <pie-text-input
                :value="username"
                @input="username = $event.target.value"
                class="form-field"
                id="username"
                data-test-id="username"
                name="username"
                type="text">
                <icon-user slot="leadingIcon"></icon-user>
            </pie-text-input>

            <pie-form-label for="favouriteNumber">
                Favourite Number:
            </pie-form-label>
            <pie-text-input
                :value="favouriteNumber"
                @input="handleFavouriteNumberInput"
                :assistiveText="favouriteNumberValidationMessage"
                :status="favouriteNumberValidationMessage.length ? 'error' : 'default'"
                class="form-field"
                id="favouriteNumber"
                data-test-id="favouriteNumber"
                name="favouriteNumber"
                :min="-5"
                :max="200"
                type="number">
                <icon-number-symbol slot="leadingIcon"></icon-number-symbol>
            </pie-text-input>

            <pie-form-label for="email">
                Email:
            </pie-form-label>
            <pie-text-input
                :value="email"
                @input="email = $event.target.value"
                class="form-field"
                id="email"
                data-test-id="email"
                name="email"
                type="email">
                <icon-email slot="leadingIcon"></icon-email>
            </pie-text-input>

            <pie-form-label for="url">
                Website:
            </pie-form-label>
            <pie-text-input
                :value="url"
                @input="url = $event.target.value"
                class="form-field"
                id="url"
                data-test-id="url"
                name="url"
                type="url">
                <icon-laptop slot="leadingIcon"></icon-laptop>
            </pie-text-input>

            <pie-form-label for="tel">
                Telephone:
            </pie-form-label>
            <pie-text-input
                :value="tel"
                @input="tel = $event.target.value"
                class="form-field"
                id="tel"
                data-test-id="tel"
                name="tel"
                type="tel">
                <icon-phone slot="leadingIcon"></icon-phone>
            </pie-text-input>

            <pie-form-label for="password">
                Password:
            </pie-form-label>
            <pie-text-input
                :value="password"
                @input="password = $event.target.value"
                class="form-field"
                id="password"
                data-test-id="password"
                name="password"
                type="password">
                <icon-key slot="leadingIcon"></icon-key>
            </pie-text-input>

            <pie-form-label for="description">
               Description:
            </pie-form-label>
            <pie-textarea
                :value="description"
                placeholder="Write something about yourself..."
                @input="description = $event.target.value"
                class="form-field"
                id="description"
                data-test-id="description"
                name="description">
            </pie-textarea>

            <div class="form-controls">
                <pie-form-label for="approveSettings">
                    Approve settings
                </pie-form-label>
                <pie-switch
                    id="approveSettings"
                    data-test-id="approveSettings"
                    name="approveSettings"
                    @change="approveSettings = $event.target.checked"
                    :checked="approveSettings"></pie-switch>
                <pie-switch
                    label="Enable Notifications"
                    id="notifications"
                    data-test-id="enableNotifications"
                    name="notifications"
                    @change="notifications = $event.target.checked"
                    :checked="notifications"></pie-switch>
                <pie-checkbox
                    id="newsletter"
                    data-test-id="newsletterSignup"
                    name="newsletter"
                    @change="newsletter = $event.target.checked"
                    :checked="newsletter">
                    Receive discounts, loyalty offers and other updates via email
                </pie-checkbox>

                <fieldset>
                    <pie-radio
                        value="radio-1"
                        name="radioValue"
                        @change="radio = $event.target.value">
                        Radio 1
                    </pie-radio>
                    <pie-radio
                        data-test-id="radio-2"
                        value="radio-2"
                        name="radioValue"
                        @change="radio = $event.target.value">
                        Radio 2
                    </pie-radio>
                </fieldset>

                <pie-checkbox-group>
                    <pie-form-label slot="label">Choose the way we can contact you:</pie-form-label>
                    <pie-checkbox
                        id="contactByEmail"
                        name="contactByEmail"
                        data-test-id="contactByEmail"
                        @change="contactByEmail = $event.target.checked"
                        :checked="contactByEmail">
                        Contact By Email
                    </pie-checkbox>
                    <pie-checkbox
                        id="contactByPhone"
                        name="contactByPhone"
                        data-test-id="contactByPhone"
                        @change="contactByPhone = $event.target.checked"
                        :checked="contactByPhone">
                        Contact By Phone
                    </pie-checkbox>
                </pie-checkbox-group>
            </div>
            <div class="form-btns">
                <pie-button class="form-btn" data-test-id="reset-btn" variant="secondary" type="reset">Reset</pie-button>
                <pie-button class="form-btn" data-test-id="submit-btn" type="submit">Submit</pie-button>
            </div>
        </form>
        <div id="output" v-if="formDataDisplay.length" data-test-id="output">
            <h2>Form Data</h2>
            <pre data-test-id="outputData">
                {{ formDataDisplay }}
            </pre>
        </div>
    </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { definePageMeta } from "#imports";
import '@justeattakeaway/pie-webc/components/button.js';
import '@justeattakeaway/pie-webc/components/form-label.js';
import '@justeattakeaway/pie-webc/components/text-input.js';
import '@justeattakeaway/pie-webc/components/textarea.js';
import '@justeattakeaway/pie-webc/components/radio.js';
import '@justeattakeaway/pie-webc/components/switch.js';
import '@justeattakeaway/pie-webc/components/checkbox.js';
import '@justeattakeaway/pie-webc/components/checkbox-group.js';
import '@justeattakeaway/pie-icons-webc/dist/IconEmail.js';
import '@justeattakeaway/pie-icons-webc/dist/IconLaptop.js';
import '@justeattakeaway/pie-icons-webc/dist/IconPhone.js';
import '@justeattakeaway/pie-icons-webc/dist/IconUser.js';
import '@justeattakeaway/pie-icons-webc/dist/IconNumberSymbol.js';
import '@justeattakeaway/pie-icons-webc/dist/IconKey.js';

definePageMeta({
  title: 'PIE Form Test Page',
});

const username = ref('');
const email = ref('');
const tel = ref('');
const url = ref('');
const password = ref('');
const approveSettings = ref(false);
const notifications = ref(false);
const favouriteNumber = ref('');
const favouriteNumberValidationMessage = ref('');
const newsletter = ref(false);
const description = ref('');
const radio = ref('');

const contactByEmail = ref(false);
const contactByPhone = ref(false);

const formDataDisplay = ref('');

function handleFavouriteNumberInput(event: Event) {
    const inputElement = event.target as HTMLInputElement;
    const value = inputElement.value;
    favouriteNumber.value = value;

    let validationMessage = '';
    if (inputElement.validity.rangeUnderflow) {
        validationMessage = 'The favourite number is too low. Please pick a number between -5 and 200.';
    } else if (inputElement.validity.rangeOverflow) {
        validationMessage = 'The favourite number is too high. Please pick a number between -5 and 200.';
    }

    favouriteNumberValidationMessage.value = validationMessage;
}

function handleSubmit() {
    formDataDisplay.value = JSON.stringify({
        username: username.value,
        email: email.value,
        tel: tel.value,
        url: url.value,
        radioValue: radio.value,
        password: password.value,
        approveSettings: approveSettings.value,
        enableNotifications: notifications.value,
        favouriteNumber: favouriteNumber.value,
        newsletterSignup: newsletter.value,
        description: description.value,
        contactByEmail: contactByEmail.value,
        contactByPhone: contactByPhone.value,
    }, null, 2);
}
</script>
<style scoped>
     /* Form Styles */
    .form {
        display: flex;
        flex-direction: column;
    }

    .form-field {
        margin-bottom: var(--dt-spacing-b);
    }

    .form-controls {
        margin-top: var(--dt-spacing-e);
        > * {
            display: block;
        }

        > * + * {
            margin-top: var(--dt-spacing-b);
        }
    }

    .form-btns {
        margin-top: var(--dt-spacing-c);
        display: flex;
        gap: var(--dt-spacing-a)
    }

    .form-btns > .form-btn:first-of-type {
        margin-left: auto;
    }
</style>

// nextjs-app-v14/src/app/integrations/form/form.tsx
'use client';

import React, { useState } from 'react';
import NavigationLayout from '@/app/layout/navigation';
import { PieFormLabel } from '@justeattakeaway/pie-webc/react/form-label.js';
import { PieRadio } from '@justeattakeaway/pie-webc/react/radio.js';
import { PieSwitch } from '@justeattakeaway/pie-webc/react/switch.js';
import { PieButton } from '@justeattakeaway/pie-webc/react/button.js';
import { PieTextInput } from '@justeattakeaway/pie-webc/react/text-input.js';
import { PieTextarea } from '@justeattakeaway/pie-webc/react/textarea.js';
import { PieCheckbox } from '@justeattakeaway/pie-webc/react/checkbox.js';
import { PieCheckboxGroup } from '@justeattakeaway/pie-webc/react/checkbox-group.js';
import { IconEmail } from '@justeattakeaway/pie-icons-webc/dist/react/IconEmail.js';
import { IconLaptop } from '@justeattakeaway/pie-icons-webc/dist/react/IconLaptop.js';
import { IconPhone } from '@justeattakeaway/pie-icons-webc/dist/react/IconPhone.js';
import { IconUser } from '@justeattakeaway/pie-icons-webc/dist/react/IconUser.js';
import { IconNumberSymbol } from '@justeattakeaway/pie-icons-webc/dist/react/IconNumberSymbol.js';
import { IconKey } from '@justeattakeaway/pie-icons-webc/dist/react/IconKey.js';
import '@/styles/form.scss';

export default function Form() {
    const [approveSettings, setApproveSettings] = useState(false);
    const [enableNotifications, setNotifications] = useState(false);
    const [newsletterSignup, setNewsletterSignup] = useState(false);
    const [contactByPhone, setContactByPhone] = useState(false);
    const [contactByEmail, setContactByEmail] = useState(false);
    const [favouriteNumber, setFavouriteNumber] = useState('');
    const [favouriteNumberValidationMessage, setFavouriteNumberValidationMessage] = useState('');
    const [radioValue, setRadioValue] = useState('');

    const [formDataDisplay, setFormDataDisplay] = useState<string | null>(null);

    const [username, setUsername] = useState('');
    const [url, setUrl] = useState('');
    const [tel, setTel] = useState('');

    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [description, setDescription] = useState('');

    const handleUsernameInput = (event: InputEvent) => {
        setUsername((event.target as HTMLInputElement).value);
    }

    const handleFavouriteNumberInput = (event: InputEvent) => {
        const inputElement = event.target as HTMLInputElement;
        const value = inputElement.value;

        // Set the state based on the input. If the input is empty, value will be '', effectively clearing the input field.
        setFavouriteNumber(value);

        let validationMessage = '';

        if (value && inputElement.validity.rangeUnderflow) {
            validationMessage = 'The favourite number is too low. Please pick a number between -5 and 200.';
        } else if (value && inputElement.validity.rangeOverflow) {
            validationMessage = 'The favourite number is too high. Please pick a number between -5 and 200.';
        }

        setFavouriteNumberValidationMessage(validationMessage);
    };

    const handleEmailInput = (event: InputEvent) => {
        setEmail((event.target as HTMLInputElement).value);
    }

    const handleUrlInput = (event: InputEvent) => {
        setUrl((event.target as HTMLInputElement).value);
    }

    const handleTelInput = (event: InputEvent) => {
        setTel((event.target as HTMLInputElement).value);
    }

    const handlePasswordInput = (event: InputEvent) => {
        setPassword((event.target as HTMLInputElement).value);
    }

    const handleRadioInput = (event: InputEvent) => {
        setRadioValue((event.target as HTMLInputElement).value);
    };

    const handleApproveSettingsChange = () => {
        setApproveSettings(current => !current);
    };

    const handleNotificationsChange = () => {
        setNotifications(current => !current);
    };

    const handleNewsletterSignup = () => {
        setNewsletterSignup(current => !current);
    };

    const handleDescriptionTextarea = (event: InputEvent) => {
        setDescription((event.target as HTMLTextAreaElement).value);
    }

    const handleContactByPhone = () => {
        setContactByPhone(current => !current);
    };

    const handleContactByEmail = () => {
        setContactByEmail(current => !current);
    };

    const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
        event.preventDefault();
        const data = {
            approveSettings,
            enableNotifications,
            newsletterSignup,
            contactByEmail,
            contactByPhone,
            username,
            favouriteNumber,
            email,
            url,
            tel,
            password,
            radioValue,
            description,
        };

        setFormDataDisplay(JSON.stringify(data, null, 2));
    };

    return (
        <NavigationLayout title="Form Test Page">
            <form className="form" id="testForm" onSubmit={handleSubmit}>
                <PieFormLabel for="username">
                    Username:
                </PieFormLabel>
                <PieTextInput
                    className="form-field"
                    id="username"
                    data-test-id="username"
                    name="username"
                    value={username}
                    onInput={handleUsernameInput as any}
                    type="text">
                    <IconUser slot="leadingIcon"></IconUser>
                </PieTextInput>

                <PieFormLabel for="favouriteNumber">
                    Favourite Number:
                </PieFormLabel>
                <PieTextInput
                    className="form-field"
                    id="favouriteNumber"
                    data-test-id="favouriteNumber"
                    name="favouriteNumber"
                    min={-5}
                    max={200}
                    value={favouriteNumber}
                    onInput={handleFavouriteNumberInput as any} // Ensure type compatibility
                    type="number"
                    assistiveText={favouriteNumberValidationMessage}
                    status={favouriteNumberValidationMessage ? 'error' : 'default'}
                >
                    <IconNumberSymbol slot="leadingIcon"></IconNumberSymbol>
                </PieTextInput>

                <PieFormLabel for="email">
                    Email:
                </PieFormLabel>
                <PieTextInput
                    className="form-field"
                    id="email"
                    data-test-id="email"
                    name="email"
                    value={email}
                    onInput={handleEmailInput as any}
                    type="email">
                    <IconEmail slot="leadingIcon"></IconEmail>
                </PieTextInput>

                <PieFormLabel for="url">
                    Website:
                </PieFormLabel>
                <PieTextInput
                    className="form-field"
                    id="url"
                    data-test-id="url"
                    name="url"
                    value={url}
                    onInput={handleUrlInput as any}
                    type="url">
                    <IconLaptop slot="leadingIcon"></IconLaptop>
                </PieTextInput>

                <PieFormLabel for="tel">
                    Telephone:
                </PieFormLabel>
                <PieTextInput
                    className="form-field"
                    id="tel"
                    data-test-id="tel"
                    name="tel"
                    value={tel}
                    onInput={handleTelInput as any}
                    type="tel">
                    <IconPhone slot="leadingIcon"></IconPhone>
                </PieTextInput>

                <PieFormLabel for="password">
                    Password:
                </PieFormLabel>
                <PieTextInput
                    className="form-field"
                    id="password"
                    data-test-id="password"
                    name="password"
                    value={password}
                    onInput={handlePasswordInput as any}
                    type="password">
                    <IconKey slot="leadingIcon"></IconKey>
                </PieTextInput>

                <PieFormLabel for="description">
                    Description:
                </PieFormLabel>
                <PieTextarea
                    className="form-field"
                    id="description"
                    data-test-id="description"
                    name="description"
                    placeholder="Write something about yourself..."
                    value={description}
                    onInput={handleDescriptionTextarea as any}/>

                <div className="form-controls">
                    <PieFormLabel for="approveSettings">
                        Approve settings
                    </PieFormLabel>
                    <PieSwitch
                        id="approveSettings"
                        data-test-id="approveSettings"
                        name="approveSettings"
                        checked={approveSettings}
                        onChange={handleApproveSettingsChange}
                    />
                    <PieSwitch
                        label="Enable Notifications"
                        id="enableNotifications"
                        data-test-id="enableNotifications"
                        name="enableNotifications"
                        checked={enableNotifications}
                        onChange={handleNotificationsChange}
                    />
                    <PieCheckbox
                        id="newsletterSignup"
                        data-test-id="newsletterSignup"
                        name="newsletterSignup"
                        checked={newsletterSignup}
                        onChange={handleNewsletterSignup}>
                        Receive discounts, loyalty offers and other updates via email
                    </PieCheckbox>
                    <PieCheckboxGroup>
                        <PieFormLabel slot="label">Choose the way we can contact you:</PieFormLabel>
                        <PieCheckbox
                            id="contactByEmail"
                            data-test-id="contactByEmail"
                            checked={contactByEmail}
                            name="contactByEmail"
                            onChange={handleContactByEmail}>
                            Contact By Email
                        </PieCheckbox>
                        <PieCheckbox
                            id="contactByPhone"
                            data-test-id="contactByPhone"
                            checked={contactByPhone}
                            name="contactByPhone"
                            onChange={handleContactByPhone}>
                            Contact By Phone
                        </PieCheckbox>
                    </PieCheckboxGroup>

                    <fieldset>
                        <PieRadio value="radio-1" name="radio-group" onInput={handleRadioInput as any}>Radio 1</PieRadio>
                        <PieRadio value="radio-2" name="radio-group" onInput={handleRadioInput as any}>Radio 2</PieRadio>
                    </fieldset>
                </div>
                <div className='form-btns'>
                    <PieButton className="form-btn" data-test-id="reset-btn" variant="secondary" type="reset">Reset</PieButton>
                    <PieButton className="form-btn" data-test-id="submit-btn" type="submit">Submit</PieButton>
                </div>
            </form>
            {formDataDisplay && (
                <div id="output">
                    <h2>Form Data</h2>
                    <pre data-test-id="outputData">{formDataDisplay}</pre>
                </div>
            )}
        </NavigationLayout>
    );
}
