// nuxt-app/pages/components/textarea.vue
<template>
    <div>
        <pie-textarea value="foo"></pie-textarea>
        <pie-divider></pie-divider>
        <pie-textarea resize="manual" value="foo"></pie-textarea>
        <pie-divider></pie-divider>
        <pie-form-label :trailing="`${count} / ${maxLength}`">Label</pie-form-label>
        <pie-textarea
            :value="textAreaInput"
            :maxlength="maxLength"
            @input="handleInput"
        ></pie-textarea>
    </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { definePageMeta } from '#imports';
import '@justeattakeaway/pie-webc/components/textarea.js';
import '@justeattakeaway/pie-webc/components/divider.js';
import '@justeattakeaway/pie-webc/components/form-label.js';

definePageMeta({
    title: 'Textarea',
});

const maxLength = 20;
const textAreaInput = ref('');
const count = ref(0);

function handleInput(e: Event) {
    textAreaInput.value = (e.target as HTMLTextAreaElement).value;
    count.value = textAreaInput.value.length;
}
</script>

// nextjs-app-v14/src/app/components/textarea/textarea.tsx
'use client';

import NavigationLayout from "@/app/layout/navigation";
import { useState } from "react";
import { PieTextarea } from '@justeattakeaway/pie-webc/react/textarea.js';
import { PieDivider } from '@justeattakeaway/pie-webc/react/divider.js';
import { PieFormLabel } from '@justeattakeaway/pie-webc/react/form-label.js';

export default function Textarea() {
    const maxLength = 20;
    const [value, setValue] = useState('');
    const count = value.length;

    return (
        <NavigationLayout title="Textarea">
            <PieTextarea value="foo" />

            <PieDivider />

            <PieTextarea
                value="foo"
                resize="manual"
            />

            <PieDivider />

            <PieFormLabel trailing={`${count} / ${maxLength}`}>Label</PieFormLabel>
            <PieTextarea
                value={value}
                maxlength={maxLength}
                onInput={(e) => setValue((e.target as HTMLTextAreaElement).value)}
            />

        </NavigationLayout>
    );
}
