// nuxt-app/pages/components/data-table/table-noheader.vue
<template>
    <NuxtLayout name="default" :parent-link="{ href: '/components/data-table', label: 'Back to Data Table variants' }">
        <h2>Table with no header</h2>
        <pie-data-table
            :columns="sampleColumns"
            :data="sampleData"
            data-test-id="PieDataTable"
        ></pie-data-table>
    </NuxtLayout>
</template>

<script setup lang="ts">
import { definePageMeta } from '#imports';
import '@justeattakeaway/pie-webc/components/data-table.js';
import { sampleColumns, sampleData } from '../../../data/sampleTableData';

definePageMeta({
    title: 'DataTable - No Header',
    layout: false,
});
</script>

// nextjs-app-v14/src/app/components/data-table/table-noheader/table-noheader.tsx
'use client';

import NavigationLayout from "@/app/layout/navigation";
import { PieDataTable } from '@justeattakeaway/pie-webc/react/data-table.js';
import { sampleColumns, sampleData } from '../sample-table-data';

export default function TableNoHeader() {
    return (
        <NavigationLayout
            title="DataTable - No Header"
            parentLink={{ href: '/components/data-table', label: 'Back to Data Table variants' }}
        >
            <h2>Table with no header</h2>
            <PieDataTable columns={sampleColumns} data={sampleData}
                data-test-id="PieDataTable"
            ></PieDataTable>
        </NavigationLayout>
    );
}
