// nuxt-app/pages/components/toast-provider.vue
<template>
  <div>
    <pie-toast-provider :options="toastOptions"
      @pie-toast-provider-queue-update="handleQueueUpdate"></pie-toast-provider>

    <pie-tag data-test-id="toast-queue-length" variant="information" style="margin-top: 16px;">
      Toast Queue Length: {{ queueLength }}
    </pie-tag>

    <div style="margin-top: 16px; display: flex; gap: 16px; flex-wrap: wrap;">
      <pie-button data-test-id="info-toast-btn" @click="triggerInfoToast">Trigger Info Toast (Low Priority)</pie-button>
      <pie-button data-test-id="warning-toast-btn" @click="triggerWarningToast">Trigger Warning Toast (Medium
        Priority)</pie-button>
      <pie-button data-test-id="error-toast-btn" @click="triggerErrorToast">Trigger Error Toast (High
        Priority)</pie-button>
      <pie-button data-test-id="clear-toasts-btn" variant="secondary" @click="clearToasts">Clear All Toasts</pie-button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { definePageMeta } from '#imports';
import { ref } from 'vue';
import { toaster } from '@justeattakeaway/pie-webc/components/toast-provider.js';
import '@justeattakeaway/pie-webc/components/toast-provider.js';
import '@justeattakeaway/pie-webc/components/button.js';
import '@justeattakeaway/pie-webc/components/tag.js';

definePageMeta({
  title: 'Toast Provider',
});

const toastOptions = ref({
  isDismissible: true,
  onPieToastOpen: () => console.log('Toast Opened'),
  onPieToastClose: () => console.log('Toast Closed'),
  onPieToastLeadingActionClick: () => console.log('Leading Action Clicked'),
});

const queueLength = ref(0);

const handleQueueUpdate = (event: CustomEvent) => {
  queueLength.value = event.detail.length;
};

const triggerInfoToast = () => {
  toaster.create({
    message: 'Low Priority Info',
    variant: 'info',
  });
};

const triggerWarningToast = () => {
  toaster.create({
    message: 'Medium Priority Warning Toast',
    variant: 'warning',
  });
};

const triggerErrorToast = () => {
  toaster.create({
    message: 'High Priority Error Toast',
    variant: 'error',
  });
};

const clearToasts = () => {
  toaster.clearAll();
};
</script>

// nextjs-app-v15/src/app/components/toast-provider/toast-provider.tsx
'use client';

import { useState } from 'react';
import NavigationLayout from '@/app/layout/navigation';
import { PieToastProvider } from '@justeattakeaway/pie-webc/react/toast-provider.js';
import { toaster } from '@justeattakeaway/pie-webc/components/toast-provider.js';
import { PieButton } from '@justeattakeaway/pie-webc/react/button.js';
import { PieTag } from '@justeattakeaway/pie-webc/react/tag.js';

export default function ToastProviderPage() {
    const [queueLength, setQueueLength] = useState(0);

    const handleQueueUpdate = (event: CustomEvent) => {
        setQueueLength(event.detail.length);
    };

    return (
        <NavigationLayout title="Toast Provider">
            <PieToastProvider
                options={{
                    isDismissible: true,
                    onPieToastOpen: () => console.log('Toast Opened'),
                    onPieToastClose: () => console.log('Toast Closed'),
                    onPieToastLeadingActionClick: () => console.log('Leading Action Clicked'),
                }}
                onPieToastProviderQueueUpdate={handleQueueUpdate}
            />

            <PieTag
                data-test-id="toast-queue-length"
                variant="information"
                style={{ marginTop: '16px' }}>
                Toast Queue Length: {queueLength}
            </PieTag>

            <div style={{ marginTop: '16px', display: 'flex', gap: '16px', flexWrap: 'wrap' }}>
                <PieButton
                    data-test-id="info-toast-btn"
                    onClick={() =>
                        toaster.create({
                            message: 'Low Priority Info',
                            variant: 'info',
                        })
                    }
                >
                    Trigger Info Toast (Low Priority)
                </PieButton>

                <PieButton
                    data-test-id="warning-toast-btn"
                    onClick={() =>
                        toaster.create({
                            message: 'Medium Priority Warning Toast',
                            variant: 'warning',
                        })
                    }
                >
                    Trigger Warning Toast (Medium Priority)
                </PieButton>

                <PieButton
                    data-test-id="error-toast-btn"
                    onClick={() =>
                        toaster.create({
                            message: 'High Priority Error Toast',
                            variant: 'error',
                        })
                    }
                >
                    Trigger Error Toast (High Priority)
                </PieButton>

                <PieButton
                    data-test-id="clear-toasts-btn"
                    variant="secondary"
                    onClick={() => toaster.clearAll()}>
                    Clear All Toasts
                </PieButton>
            </div>
        </NavigationLayout>
    );
}
