// nextjs-app-v15/src/app/components/accordion/accordion.tsx
'use client';

import NavigationLayout from "@/app/layout/navigation";
import { PieAccordion } from '@justeattakeaway/pie-webc/react/accordion.js';
import { IconPie } from '@justeattakeaway/pie-icons-webc/dist/react/IconPie';
import { IconRocketShip } from '@justeattakeaway/pie-icons-webc/dist/react/IconRocketShip';
import { useState } from "react";

export default function Accordion() {
    const [isFirstOpen, setIsFirstOpen] = useState(true);
    const [isSecondOpen, setIsSecondOpen] = useState(false);

    const handleFirstToggle = (event: CustomEvent<{ isOpen: boolean }>) => {
        setIsFirstOpen(!event.detail.isOpen);
    };

    const handleSecondToggle = (event: CustomEvent<{ isOpen: boolean }>) => {
        setIsSecondOpen(!event.detail.isOpen);
    };

    return (
        <NavigationLayout title="Accordion">
            <PieAccordion
                headingLabel="What is PIE?"
                isOpen={isFirstOpen}
                onPieAccordionToggle={handleFirstToggle}
            >
                <IconPie slot="icon" size="m" />
                PIE is the design system used across Just Eat Takeaway products. It provides a consistent set of components and styles.
            </PieAccordion>

            <PieAccordion
                headingLabel="How do I get started?"
                secondaryLabel="Installation and setup guide"
                isOpen={isSecondOpen}
                onPieAccordionToggle={handleSecondToggle}
                isDividerHidden={true}
            >
                <IconRocketShip slot="icon" size="m" />
                Install the pie-webc package and import the components you need. See the documentation for more details.
            </PieAccordion>
        </NavigationLayout>
    );
}

// nuxt-app/pages/components/accordion.vue
<template>
  <div>
    <pie-accordion
      headingLabel="What is PIE?"
      :isOpen="isFirstOpen"
      @pie-accordion-toggle="handleFirstToggle"
    >
      <icon-pie slot="icon" size="m"></icon-pie>
      PIE is the design system used across Just Eat Takeaway products. It provides a consistent set of components and styles.
    </pie-accordion>

    <pie-accordion
      headingLabel="How do I get started?"
      secondaryLabel="Installation and setup guide"
      :isOpen="isSecondOpen"
      :isDividerHidden="true"
      @pie-accordion-toggle="handleSecondToggle"
    >
      <icon-rocket-ship slot="icon" size="m"></icon-rocket-ship>
      Install the pie-webc package and import the components you need. See the documentation for more details.
    </pie-accordion>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { definePageMeta } from '#imports';
import '@justeattakeaway/pie-webc/components/accordion.js';
import '@justeattakeaway/pie-icons-webc/dist/IconPie.js';
import '@justeattakeaway/pie-icons-webc/dist/IconRocketShip.js';

definePageMeta({
    title: 'Accordion',
});

const isFirstOpen = ref(true);
const isSecondOpen = ref(false);

function handleFirstToggle(event: CustomEvent) {
    isFirstOpen.value = !event.detail.isOpen;
}

function handleSecondToggle(event: CustomEvent) {
    isSecondOpen.value = !event.detail.isOpen;
}
</script>
