// nextjs-app-v13/src/pages/components/assistive-text.tsx
import NavigationLayout from "@/layout/navigation";
import { PieAssistiveText } from "@justeattakeaway/pie-assistive-text/dist/react";

export default function AssistiveText() {
    return (
        <NavigationLayout title="Assistive Text">
        <PieAssistiveText>Assistive Text</PieAssistiveText>
        <PieAssistiveText variant="success">Assistive Text</PieAssistiveText>
        <PieAssistiveText variant="error">Assistive Text</PieAssistiveText>
        </NavigationLayout>
    );
}

// nuxt-app/pages/components/assistive-text.vue
<template>
	<div>
		<pie-assistive-text variant="default">Assistive Text Default</pie-assistive-text>
		<pie-assistive-text variant="success">Assistive Text Success</pie-assistive-text>
		<pie-assistive-text variant="error">Assistive Text Error</pie-assistive-text>
	</div>
</template>

<script setup lang="ts">
import { definePageMeta, onBeforeMount } from '#imports';
import { PieAssistiveText } from '@justeattakeaway/pie-assistive-text';

definePageMeta({
    title: 'PIE Assistive Text',
});
</script>
