// nextjs-app-v14/src/app/components/assistive-text/assistive-text.tsx
'use client';

import NavigationLayout from "@/app/layout/navigation";
import { PieAssistiveText } from '@justeattakeaway/pie-webc/react/assistive-text.js';

export default function AssistiveText() {
    return (
        <NavigationLayout title="Assistive Text">
        <PieAssistiveText message="Assistive Text"></PieAssistiveText>
        <PieAssistiveText variant="success" message="Assistive Text"></PieAssistiveText>
        <PieAssistiveText variant="error" message="Assistive Text"></PieAssistiveText>
        </NavigationLayout>
    );
}

// nuxt-app/pages/components/assistive-text.vue
<template>
	<div>
		<pie-assistive-text variant="default" message="Assistive Text Default"></pie-assistive-text>
		<pie-assistive-text variant="success" message="Assistive Text Success"></pie-assistive-text>
		<pie-assistive-text variant="error" message="Assistive Text Error"></pie-assistive-text>
	</div>
</template>

<script setup lang="ts">
import { definePageMeta } from '#imports';
import '@justeattakeaway/pie-webc/components/assistive-text.js';

definePageMeta({
    title: 'Assistive Text',
});
</script>
