// nextjs-app-v14/src/app/components/button/button.tsx
'use client';

import NavigationLayout from "@/app/layout/navigation";
import { PieButton } from '@justeattakeaway/pie-webc/react/button.js';
import { PieDivider } from '@justeattakeaway/pie-webc/react/divider.js';
import { IconSearch } from '@justeattakeaway/pie-icons-webc/dist/react/IconSearch.js';
import { useState } from "react";

export default function Button() {
    const [counter, setCounter] = useState(0);

    return (
        <NavigationLayout title="Button">
        <PieButton onClick={() => setCounter(counter + 1)}>Counter: {counter}</PieButton>

        <PieDivider />

        <h2>PIE Button - with Icon and text</h2>
        <PieButton>
            <IconSearch slot="icon"></IconSearch>
            Search
        </PieButton>

        <PieDivider />

        <h2>PIE Button - multi-line content</h2>
        <PieButton>
            This button has a long text that will wrap to the next line. It‘s very long
        </PieButton>

        <PieDivider />

        <h2>PIE Button - truncated content</h2>
        <PieButton isFullWidth>
            Thisisawordthatdoesntactuallyexistsothatwecanseehowthecontentistruncated
        </PieButton>
        </NavigationLayout>
    );
}

// nuxt-app/pages/components/button.vue
<template>
  <div>
    <pie-button @click="setCounter">
      Counter: {{ counter }}
    </pie-button>

    <pie-divider></pie-divider>

    <h2>PIE Button - with Icon and text</h2>
    <pie-button>
        <icon-search slot="icon"></icon-search>
        Search TEST
    </pie-button>

    <pie-divider></pie-divider>

    <h2>PIE Button - multi-line content</h2>
    <pie-button>
        This button has a long text that will wrap to the next line. It‘s very long
    </pie-button>

    <pie-divider></pie-divider>

    <h2>PIE Button - truncated content</h2>
    <pie-button isFullWidth>
        Thisisawordthatdoesntactuallyexistsothatwecanseehowthecontentistruncated
    </pie-button>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { definePageMeta } from '#imports';
import '@justeattakeaway/pie-webc/components/button.js';
import '@justeattakeaway/pie-webc/components/divider.js';
import '@justeattakeaway/pie-icons-webc/dist/IconSearch.js';

definePageMeta({
    title: 'Button',
});

let counter = ref(0);

function setCounter() {
  counter.value++;
}
</script>
