// nextjs-app/src/pages/components/button.tsx
import { PieButton } from "@justeattakeaway/pie-button/dist/react";
import { useState } from "react";

export default function Button() {
    const [counter, setCounter] = useState(0);

    return (
        <>
        <PieButton onClick={() => setCounter(counter + 1)}>Counter: {counter}</PieButton>
        </>
    );
}

// nuxt-app/pages/components/button.vue
<template>
  <div>
    <pie-button @click="setCounter">
      Counter: {{ counter }}
    </pie-button>
  </div>
</template>

<script setup lang="ts">
import '@justeattakeaway/pie-button';
import { ref } from 'vue';
import { definePageMeta } from '#imports';

definePageMeta({
    title: 'PIE Button',
});

let counter = ref(0);

function setCounter() {
  counter.value++;
}
</script>
