// nextjs-app-v13/src/pages/components/card.tsx
import NavigationLayout from "@/layout/navigation";
import { PieCard } from '@justeattakeaway/pie-webc/react/card.js';

export default function Card() {
    return (
        <NavigationLayout title="Card">
        <PieCard padding="a">
            <h2>Default Card</h2>
            <p>Lorem ipsum dolor sit amet
                consectetur adipisicing elit.
                Fugiat dolore dolorem maxime,
                quod, in minima esse fugit
                distinctio, officia et soluta
                dicta consequuntur commodi officiis
                tempora asperiores aspernatur atque quas.
            </p>
        </PieCard>
        </NavigationLayout>
    );
}

// nuxt-app/pages/components/card.vue
<template>
  <div>
    <pie-card>
      <h2>Default Card</h2>
      <p>Lorem ipsum dolor sit amet
        consectetur adipisicing elit.
        Fugiat dolore dolorem maxime,
        quod, in minima esse fugit
        distinctio, officia et soluta
        dicta consequuntur commodi officiis
        tempora asperiores aspernatur atque quas.</p>
    </pie-card>
  </div>
</template>

<script setup lang="ts">
import { definePageMeta } from '#imports';
import '@justeattakeaway/pie-webc/components/card.js';

definePageMeta({
    title: 'Card',
});
</script>
