// nextjs-app-v13/src/pages/components/checkbox-group.tsx
'use client';

import React, { useState } from "react";
import NavigationLayout from "@/layout/navigation";
import { PieCheckbox } from "@justeattakeaway/pie-webc/react/checkbox.js";
import { PieCheckboxGroup } from "@justeattakeaway/pie-webc/react/checkbox-group.js";
import { PieFormLabel } from "@justeattakeaway/pie-webc/react/form-label.js";

export default function CheckboxGroup() {
    const [contactByPhone, setContactByPhone] = useState(false);
    const [contactByEmail, setContactByEmail] = useState(false);

    const handleContactByPhone = () => {
        setContactByPhone(current => !current);
    };

    const handleContactByEmail = () => {
        setContactByEmail(current => !current);
    };

    return (
        <NavigationLayout title="Checkbox Group">
            <PieCheckboxGroup>
                <PieFormLabel slot="label">Choose the way we can contact you:</PieFormLabel>
                <PieCheckbox
                    checked={contactByEmail}
                    onChange={handleContactByEmail}>
                    Contact By Email
                </PieCheckbox>
                <PieCheckbox
                    checked={contactByPhone}
                    onChange={handleContactByPhone}>
                    Contact By Phone
                </PieCheckbox>
            </PieCheckboxGroup>
        </NavigationLayout>
    );
}

// nuxt-app/pages/components/checkbox-group.vue
<template>
  <pie-checkbox-group>
    <pie-form-label slot="label">Choose the way we can contact you:</pie-form-label>
    <pie-checkbox
        id="contactByEmail"
        @change="contactByEmail = $event.target.checked"
        :checked="contactByEmail">
      Contact By Email
    </pie-checkbox>
    <pie-checkbox
        id="contactByPhone"
        @change="contactByPhone = $event.target.checked"
        :checked="contactByPhone">
      Contact By Phone
    </pie-checkbox>
  </pie-checkbox-group>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { definePageMeta } from '#imports';
import '@justeattakeaway/pie-webc/components/checkbox.js';
import '@justeattakeaway/pie-webc/components/checkbox-group.js';
import '@justeattakeaway/pie-webc/components/form-label.js';

definePageMeta({
  title: 'PIE Checkbox Group',
});

const contactByEmail = ref(false);
const contactByPhone = ref(false);

</script>
