// nextjs-app-v15/src/app/components/cookie-banner/cookie-banner.tsx
'use client';

import NavigationLayout from "@/app/layout/navigation";
import { PieCookieBanner } from '@justeattakeaway/pie-webc/react/cookie-banner.js';
import { PieDivider } from '@justeattakeaway/pie-webc/react/divider.js';

export default function CookieBanner() {
    return (
        <NavigationLayout title="Cookie Banner">
        <PieCookieBanner
            defaultPreferences={{functional: true, personalized: true, analytical: true}}
            language="da"
            country="dk"
            hasPrimaryActionsOnly
            cookieTechnologiesLink="https://justeattakeaway.com"
            cookieStatementLink="https://justeattakeaway.com" />

        <PieDivider />

        <PieCookieBanner
            defaultPreferences={{functional: true, personalized: true, analytical: true}}
            language="da"
            country="dk"
            hasPrimaryActionsOnly
            cookieTechnologiesLink="https://justeattakeaway.com"
            cookieStatementLink="https://justeattakeaway.com" />

        <PieDivider />

        <PieCookieBanner
            defaultPreferences={{functional: true, personalized: true, analytical: true}}
            language="da"
            country="dk"
            hasPrimaryActionsOnly
            cookieTechnologiesLink="https://justeattakeaway.com"
            cookieStatementLink="https://justeattakeaway.com" />

        </NavigationLayout>
    );
}

// nuxt-app/pages/components/cookie-banner.vue
<template>
  <div>
    <pie-cookie-banner hasPrimaryActionsOnly language="en" country="ca" cookieTechnologiesLink="https://justeattakeaway.com"
      cookieStatementLink="https://justeattakeaway.com">
    </pie-cookie-banner>
  </div>
</template>

<script setup lang="ts">
import { definePageMeta } from '#imports';
import '@justeattakeaway/pie-webc/components/cookie-banner.js';

definePageMeta({
    title: 'Cookie Banner',
});

</script>
