// nextjs-app-v15/src/app/components/divider/divider.tsx
'use client';

import NavigationLayout from "@/app/layout/navigation";
import { PieDivider } from '@justeattakeaway/pie-webc/react/divider.js';
import '@/styles/divider.scss';

export default function Divider() {
    return (
        <NavigationLayout title="Divider">
            <div className="divider-container">
                <span>Span before divider</span>
                <PieDivider label="Horizontal Divider"/>
                <span>Span after divider</span>
            </div>
            <div className="divider-container divider-container-flex">
                <span>Span before divider</span>
                <PieDivider orientation="vertical"/>
                <span>Span after divider</span>
            </div>
        </NavigationLayout>
    );
}

// nuxt-app/pages/components/divider.vue
<template>
  <div class="divider-container">
    <span>Span before divider</span>
    <pie-divider label="Horizontal Divider"/>
    <span>Span after divider</span>
  </div>
  <div class="divider-container divider-container-flex">
    <span>Span before divider</span>
    <pie-divider orientation="vertical"/>
    <span>Span after divider</span>
  </div>
</template>

<script setup lang="ts">
import { definePageMeta } from '#imports';
import '@justeattakeaway/pie-webc/components/divider.js';

definePageMeta({
    title: 'Divider',
});
</script>

<style>
.divider-container {
    height: 200px;
    margin: 100px 0;
}

.divider-container-flex {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: var(--dt-spacing-d);
}
</style>
