// nextjs-app-v14/src/app/components/form-label/page.tsx
'use client';

import NavigationLayout from "@/layout/navigation";
import { PieFormLabel } from '@justeattakeaway/pie-webc/react/form-label.js';

export default function FormLabel() {
    return (
        <NavigationLayout title="Form Label">
        <PieFormLabel>Label</PieFormLabel>
        </NavigationLayout>
    );
}

// nuxt-app/pages/components/form-label.vue
<template>
  <div>
    <pie-form-label optional="Optional" trailing="X out of X">Label</pie-form-label>
  </div>
</template>

<script setup lang="ts">
import { definePageMeta } from '#imports';
import '@justeattakeaway/pie-webc/components/form-label.js';

definePageMeta({
    title: 'Form Label',
});
</script>
