// nextjs-app-v15/src/app/components/link/link.tsx
'use client';

import NavigationLayout from "@/app/layout/navigation";
import { PieLink } from '@justeattakeaway/pie-webc/react/link.js';

export default function Link() {
    return (
        <NavigationLayout title="Link">
        <PieLink href="https://pie.design" target="_blank">Visit pie.design</PieLink>
        </NavigationLayout>
    );
}

// nuxt-app/pages/components/link.vue
<template>
  <div>
    <pie-link href="https://www.pie.design">
      Visit pie.design
    </pie-link>
  </div>
</template>

<script setup lang="ts">
import { definePageMeta } from '#imports';
import '@justeattakeaway/pie-webc/components/link.js';

definePageMeta({
    title: 'PIE Link',
});
</script>
