// nextjs-app-v15/src/app/components/list-item-radio-selection/list-item-radio-selection.tsx
'use client';

import { useState } from "react";
import NavigationLayout from "@/app/layout/navigation";
import { PieRadioGroup } from "@justeattakeaway/pie-webc/react/radio-group.js";
import { PieRadio } from "@justeattakeaway/pie-webc/react/radio.js";
import { PieListItem } from "@justeattakeaway/pie-webc/react/list-item.js";
import { PieFormLabel } from "@justeattakeaway/pie-webc/react/form-label.js";
import { PieButton } from "@justeattakeaway/pie-webc/react/button.js";

export default function ListItemRadioSelection() {
    const [deliveryLeading, setDeliveryLeading] = useState('express');
    const [deliveryTrailing, setDeliveryTrailing] = useState('locker');

    const handleDeliveryLeadingChange = (event: CustomEvent) => {
        setDeliveryLeading((event.target as HTMLInputElement).value);
    };

    const handleDeliveryTrailingChange = (event: CustomEvent) => {
        setDeliveryTrailing((event.target as HTMLInputElement).value);
    };

    return (
        <NavigationLayout title="List Item Radio Selection">

            <h2 id="radio-leading-heading" style={{ padding: '8px 0' }}>Radio group - leading control (pre-selected)</h2>
            <PieRadioGroup name="deliveryLeading" value={deliveryLeading} onChange={handleDeliveryLeadingChange}>
                <PieFormLabel slot="label">Select a delivery option: {deliveryLeading}</PieFormLabel>
                <PieListItem interactionType="radio" primaryText="Standard" secondaryText="3 to 5 days" metaText="Free" hasDivider>
                    <PieRadio slot="leading" value="standard" />
                </PieListItem>
                <PieListItem interactionType="radio" primaryText="Express" secondaryText="Next day" metaText="£2.99" hasDivider>
                    <PieRadio slot="leading" value="express" />
                </PieListItem>
                <PieListItem interactionType="radio" disabled primaryText="Collection" secondaryText="Pick up in store" hasDivider>
                    <PieRadio slot="leading" value="collection" disabled />
                </PieListItem>
                <PieListItem interactionType="radio" primaryText="Locker" secondaryText="Collect at your convenience" metaText="Free">
                    <PieRadio slot="leading" value="locker" />
                </PieListItem>
            </PieRadioGroup>

            <PieButton>Some focusable element after leading radio list</PieButton>

            <h2 id="radio-trailing-heading" style={{ padding: '8px 0' }}>Radio group - trailing control (pre-selected)</h2>
            <PieRadioGroup name="deliveryTrailing" value={deliveryTrailing} onChange={handleDeliveryTrailingChange}>
                <PieFormLabel slot="label">Select a delivery option: {deliveryTrailing}</PieFormLabel>
                <PieListItem interactionType="radio" primaryText="Standard" secondaryText="3 to 5 days" hasDivider>
                    <PieRadio slot="trailing" value="standard" />
                </PieListItem>
                <PieListItem interactionType="radio" primaryText="Express" secondaryText="Next day" hasDivider>
                    <PieRadio slot="trailing" value="express" />
                </PieListItem>
                <PieListItem interactionType="radio" disabled primaryText="Collection" secondaryText="Pick up in store" hasDivider>
                    <PieRadio slot="trailing" value="collection" disabled />
                </PieListItem>
                <PieListItem interactionType="radio" primaryText="Locker" secondaryText="Collect at your convenience">
                    <PieRadio slot="trailing" value="locker" />
                </PieListItem>
            </PieRadioGroup>

            <PieButton>Some focusable element after trailing radio list</PieButton>

        </NavigationLayout>
    );
}

// nuxt-app/pages/components/list-item-radio-selection.vue
<template>
    <div>
        <h2 id="radio-leading-heading" style="padding: 8px 0;">Radio group - leading control (pre-selected)</h2>
        <pie-radio-group name="deliveryLeading" :value="deliveryLeading" @change="deliveryLeading = $event.target.value">
            <pie-form-label slot="label">Select a delivery option: {{ deliveryLeading }}</pie-form-label>
            <pie-list-item hasDivider interactionType="radio" primaryText="Standard" secondaryText="3 to 5 days" metaText="Free">
                <pie-radio slot="leading" value="standard"></pie-radio>
            </pie-list-item>
            <pie-list-item hasDivider interactionType="radio" primaryText="Express" secondaryText="Next day" metaText="£2.99">
                <pie-radio slot="leading" value="express"></pie-radio>
            </pie-list-item>
            <pie-list-item hasDivider interactionType="radio" disabled primaryText="Collection" secondaryText="Pick up in store">
                <pie-radio slot="leading" value="collection" disabled></pie-radio>
            </pie-list-item>
            <pie-list-item interactionType="radio" primaryText="Locker" secondaryText="Collect at your convenience" metaText="Free">
                <pie-radio slot="leading" value="locker"></pie-radio>
            </pie-list-item>
        </pie-radio-group>

        <pie-button>Some focusable element after leading radio list</pie-button>

        <h2 id="radio-trailing-heading" style="padding: 8px 0;">Radio group - trailing control (pre-selected)</h2>
        <pie-radio-group name="deliveryTrailing" :value="deliveryTrailing" @change="deliveryTrailing = $event.target.value">
            <pie-form-label slot="label">Select a delivery option: {{ deliveryTrailing }}</pie-form-label>
            <pie-list-item hasDivider interactionType="radio" primaryText="Standard" secondaryText="3 to 5 days">
                <pie-radio slot="trailing" value="standard"></pie-radio>
            </pie-list-item>
            <pie-list-item hasDivider interactionType="radio" primaryText="Express" secondaryText="Next day">
                <pie-radio slot="trailing" value="express"></pie-radio>
            </pie-list-item>
            <pie-list-item hasDivider interactionType="radio" disabled primaryText="Collection" secondaryText="Pick up in store">
                <pie-radio slot="trailing" value="collection" disabled></pie-radio>
            </pie-list-item>
            <pie-list-item interactionType="radio" primaryText="Locker" secondaryText="Collect at your convenience">
                <pie-radio slot="trailing" value="locker"></pie-radio>
            </pie-list-item>
        </pie-radio-group>

        <pie-button>Some focusable element after trailing radio list</pie-button>
    </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { definePageMeta } from '#imports';
import '@justeattakeaway/pie-webc/components/radio.js';
import '@justeattakeaway/pie-webc/components/radio-group.js';
import '@justeattakeaway/pie-webc/components/list-item.js';
import '@justeattakeaway/pie-webc/components/form-label.js';
import '@justeattakeaway/pie-webc/components/button.js';

definePageMeta({
    title: 'List Item Radio Selection',
});

const deliveryLeading = ref('express');
const deliveryTrailing = ref('locker');
</script>
