// nextjs-app-v15/src/app/components/radio-group/radio-group.tsx
'use client';

import NavigationLayout from "@/app/layout/navigation";
import { PieRadio } from "@justeattakeaway/pie-webc/react/radio.js";
import { PieRadioGroup } from "@justeattakeaway/pie-webc/react/radio-group.js";
import { PieFormLabel } from "@justeattakeaway/pie-webc/react/form-label.js";
import { PieButton } from "@justeattakeaway/pie-webc/react/button.js";

import { useState } from "react";

export default function RadioGroup() {
    const [favouriteTakeaway, setFavouriteTakeaway] = useState('');


    const handleFavouriteTakeaway = (event: CustomEvent) => {
        const newFavourite = (event.target as HTMLInputElement).value;
        setFavouriteTakeaway(newFavourite);
    }

    return (
        <NavigationLayout title="Radio Group">
            <PieRadioGroup name="favouriteTakeaway" onChange={handleFavouriteTakeaway}>
                <PieFormLabel slot="label">Your favourite takeaway: { favouriteTakeaway }</PieFormLabel>
                <PieRadio value="chinese">Chinese</PieRadio>
                <PieRadio value="shawarma">Shawarma</PieRadio>
                <PieRadio value="pizza">Pizza</PieRadio>
            </PieRadioGroup>

            <br/>

            <PieRadioGroup isInline name="inlineFavouriteTakeaway">
                <PieFormLabel slot="label">Your options for takeaway - inline radio</PieFormLabel>
                <PieRadio value="italian">Italian</PieRadio>
                <PieRadio value="tahi">Thai</PieRadio>
                <PieRadio value="burgers">Burgers</PieRadio>
            </PieRadioGroup>

            <br/>

            <PieButton>Some focusable element</PieButton>
        </NavigationLayout>
    );
}

// nuxt-app/pages/components/radio-group.vue
<template>
    <div>
        <pie-radio-group name="favouriteTakeaway" @change="favouriteTakeaway = $event.target.value">
            <pie-form-label slot="label">
            Your favourite takeaway: {{ favouriteTakeaway }}
            </pie-form-label>
            <pie-radio
                value="chinese">
                Chinese
            </pie-radio>
            <pie-radio
                value="shawarma">
                Shawarma
            </pie-radio>
            <pie-radio
                value="pizza">
                Pizza
            </pie-radio>
        </pie-radio-group>

        <br/>

        <pie-radio-group isInline="true" name="inlineFavouriteTakeaway">
            <pie-form-label slot="label">
                Your options for takeaway - inline radio
            </pie-form-label>
            <pie-radio
                value="chinese">
                Chinese
            </pie-radio>
            <pie-radio
                value="shawarma">
                Shawarma
            </pie-radio>
            <pie-radio
                value="pizza">
                Pizza
            </pie-radio>
        </pie-radio-group>

        <br/>

        <pie-button>Some focusable element</pie-button>
    </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { definePageMeta } from '#imports';
import '@justeattakeaway/pie-webc/components/radio.js';
import '@justeattakeaway/pie-webc/components/radio-group.js';
import '@justeattakeaway/pie-webc/components/form-label.js';
import '@justeattakeaway/pie-webc/components/button.js';

definePageMeta({
    title: 'Radio Group',
});

const favouriteTakeaway = ref('');
</script>
