// nextjs-app-v13/src/pages/components/radio.tsx
import NavigationLayout from "@/layout/navigation";
import { PieRadio } from "@justeattakeaway/pie-webc/react/radio.js";
import { useState } from "react";

export default function Radio() {
    const [isRadioChecked, setIsRadioCheck] = useState(false);

    const handleRadioChange = () => {
        setIsRadioCheck(current => !current);
        console.log(isRadioChecked);
    };

    return (
        <NavigationLayout title="Radio">
            <PieRadio
                checked={isRadioChecked}
                value="value"
                onChange={handleRadioChange}>
                {`checked: ${isRadioChecked}`}
            </PieRadio>
        </NavigationLayout>
    );
}

// nuxt-app/pages/components/radio.vue
<template>
    <div>
      <pie-radio :checked="checked" value="value" @change="handleRadioChange">
        {{ `checked: ${checked}` }}
      </pie-radio>
    </div>
  </template>

  <script setup lang="ts">
  import { ref } from 'vue';
  import { definePageMeta } from '#imports';
  import '@justeattakeaway/pie-webc/components/radio.js';

  definePageMeta({
      title: 'Radio',
  });

  let checked = ref(false);

  function handleRadioChange() {
    checked.value = !checked.value;
  }

  </script>
