// nextjs-app-v14/src/app/components/select/select.tsx
'use client';

import NavigationLayout from "@/app/layout/navigation";
import { PieSelect, type SelectProps } from "@justeattakeaway/pie-webc/react/select.js";

export default function Select() {
    const options: SelectProps['options'] = [
        {
            tag: 'optgroup',
            label: 'Animals',
            options: [
                {
                    tag: 'option',
                    text: 'Cat',
                    value: 'cat',
                },
                {
                    tag: 'option',
                    text: 'Dog',
                    value: 'dog',
                },
            ],
        },
    ];

    return (
        <NavigationLayout title="Select">
            <PieSelect options={options} />
        </NavigationLayout>
    );
}

// nuxt-app/pages/components/select.vue
<template>
    <pie-select :options="options"></pie-select>
</template>

<script setup lang="ts">
import { definePageMeta } from '#imports';
import '@justeattakeaway/pie-webc/components/select.js';

definePageMeta({
    title: 'Select',
});

const options = [
    {
        tag: 'optgroup',
        label: 'Animal',
        options: [
            {
                tag: 'option',
                text: 'Cat',
                value: 'cat',
            },
            {
                tag: 'option',
                text: 'Dog',
                value: 'dog',
            },
        ],
    },
];

</script>
