// nextjs-app-v14/src/app/components/switch/page.tsx
'use client';

import NavigationLayout from "@/layout/navigation";
import { PieSwitch } from '@justeattakeaway/pie-webc/react/switch.js';
import { useState } from "react";

export default function Switch() {
    const [isSwitchChecked, setIsSwitchCheck] = useState(false)

    const handleSwitchChange = () => {
      setIsSwitchCheck(current => !current);
      console.log(isSwitchChecked);
    };

    return (
        <NavigationLayout title="Switch">
        <PieSwitch
            label={`checked: ${isSwitchChecked}`}
            checked={isSwitchChecked}
            onChange={handleSwitchChange}>
        </PieSwitch>
        </NavigationLayout>
    );
}

// nuxt-app/pages/components/switch.vue
<template>
  <div>
    <pie-switch :label="`checked: ${checked}`" :checked="checked" @change="handleSwitchChange">
    </pie-switch>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { definePageMeta } from '#imports';
import '@justeattakeaway/pie-webc/components/switch.js';

definePageMeta({
    title: 'Switch',
});

let checked = ref(false);

function handleSwitchChange() {
  checked.value = !checked.value;
}

</script>
