// nextjs-app-v13/src/pages/components/tag.tsx
import NavigationLayout from "@/layout/navigation";
import { PieTag, variants } from '@justeattakeaway/pie-webc/react/tag.js';
import { PieDivider } from '@justeattakeaway/pie-webc/react/divider.js';

export default function Tag() {
    return (
        <NavigationLayout title="Tag">
        <h2>Non-interactive</h2>

            <h3>Default</h3>
            <div className="c-tag-container">
                {variants.map((variant) => (
                    <PieTag
                        key={variant}
                        variant={variant}>
                        {variant}
                    </PieTag>
                ))}
            </div>

            <h3>Strong</h3>

            <div className="c-tag-container">
                {variants.map((variant) => (
                    <PieTag
                        key={variant}
                        variant={variant}
                        isStrong>
                        {variant}
                    </PieTag>
                ))}
            </div>

            <PieDivider></PieDivider>

            <h2>Interactive</h2>

            <h3>Default</h3>

            <div className="c-tag-container">
                {variants.map((variant) => (
                    <PieTag
                        isInteractive
                        key={variant}
                        variant={variant}>
                        {variant}
                    </PieTag>
                ))}
            </div>

            <h3>Strong</h3>

            <div className="c-tag-container">
                {variants.map((variant) => (
                    <PieTag
                        isInteractive
                        isStrong
                        key={variant}
                        variant={variant}>
                        {variant}
                    </PieTag>
                ))}
            </div>
        </NavigationLayout>
    );
}

// nuxt-app/pages/components/tag.vue
<template>
  <div>
    <h2>Non-interactive</h2>

    <h3>Default</h3>
    <div class="c-tag-container">
      <pie-tag
        v-for="variant in variants"
        :key="variant"
        :variant="variant">
        {{ variant }}
      </pie-tag>
    </div>

    <h3>Strong</h3>

    <div class="c-tag-container">
      <pie-tag
        v-for="variant in variants"
        :key="variant"
        isStrong
        :variant="variant">
        {{ variant }}
      </pie-tag>
    </div>

    <pie-divider></pie-divider>

    <h2>Interactive</h2>

    <h3>Default</h3>

    <div class="c-tag-container">
      <pie-tag
        v-for="variant in variants"
        :key="variant"
        isInteractive
        :variant="variant">
        {{ variant }}
      </pie-tag>
    </div>

    <h3>Strong</h3>

    <div class="c-tag-container">
      <pie-tag
        v-for="variant in variants"
        :key="variant"
        isInteractive
        isStrong
        :variant="variant">
        {{ variant }}
      </pie-tag>
    </div>
  </div>
</template>

<script setup lang="ts">
import { definePageMeta } from '#imports';
import '@justeattakeaway/pie-webc/components/tag.js';
import { variants } from '@justeattakeaway/pie-webc/components/tag.js';
import '@justeattakeaway/pie-webc/components/divider.js';

definePageMeta({
    title: 'Tag',
});
</script>

<style>
.c-tag-container {
  display: flex;
  flex-wrap: wrap;
  gap: var(--dt-spacing-b);
}
</style>
