// nextjs-app-v13/src/pages/components/text-input.tsx
import NavigationLayout from "@/layout/navigation";
import { PieTextInput } from '@justeattakeaway/pie-webc/react/text-input.js';
import { IconPhone } from '@justeattakeaway/pie-icons-webc/dist/react/IconPhone.js';

export default function TextInput() {
    return (
        <NavigationLayout title="Text Input">
            <PieTextInput value="foo">
                <IconPhone slot="leadingIcon"></IconPhone>
            </PieTextInput>
        </NavigationLayout>
    );
}

// nuxt-app/pages/components/text-input.vue
<template>
  <div>
    <pie-text-input value="foo">
      <icon-phone slot="leadingIcon"></icon-phone>
    </pie-text-input>
  </div>
</template>

<script setup lang="ts">
import { definePageMeta } from '#imports';
import '@justeattakeaway/pie-webc/components/text-input.js';
import '@justeattakeaway/pie-icons-webc/dist/IconPhone.js';

definePageMeta({
    title: 'PIE Text Input',
});
</script>
