// nextjs-app-v14/src/app/components/thumbnail/thumbnail.tsx
'use client';

import NavigationLayout from "@/app/layout/navigation";
import { PieThumbnail } from '@justeattakeaway/pie-webc/react/thumbnail.js';
import { PieDivider } from '@justeattakeaway/pie-webc/react/divider.js';

export default function Thumbnail() {
    const props = {
        src: 'https://www.pie.design/assets/img/jet-logo-narrow.svg',
        alt: 'JET logo',
    }

    const invalidSrcWithPlaceholderProps = {
        src: 'https://www.pie.design/assets/img/jet-invalid-aperture.svg',
        placeholder: {
            src: 'https://www.pie.design/assets/img/404_narrow.png',
            alt: 'Thumbnail placeholder image',
        }
    }

    return (
        <NavigationLayout title="Thumbnail">
            <h3>Default</h3>
            <PieThumbnail {...props} />
            <PieDivider />
            <h3>Outline</h3>
            <PieThumbnail variant="outline" {...props} />
            <h3>Placeholder</h3>
            <PieThumbnail {...invalidSrcWithPlaceholderProps} />
        </NavigationLayout>
    );
}

// nuxt-app/pages/components/thumbnail.vue
<template>
    <h3>Default</h3>
    <pie-thumbnail v-bind="props"></pie-thumbnail>
    <pie-divider></pie-divider>
    <h3>Outline</h3>
    <pie-thumbnail variant="outline" v-bind="props"></pie-thumbnail>
    <h3>Placeholder</h3>
    <pie-thumbnail v-bind="invalidSrcWithPlaceholderProps"></pie-thumbnail>
</template>

<script setup lang="ts">
import { definePageMeta } from '#imports';
import '@justeattakeaway/pie-webc/components/thumbnail.js';
import '@justeattakeaway/pie-webc/components/divider.js';

definePageMeta({
    title: 'Thumbnail',
});

const props = {
    src: 'https://www.pie.design/assets/img/jet-logo-narrow.svg',
    alt: 'JET logo'
};

const invalidSrcWithPlaceholderProps = {
    src: 'https://www.pie.design/assets/img/jet-invalid-aperture.svg',
    placeholder: {
        src: 'https://www.pie.design/assets/img/404_narrow.png',
        alt: 'Thumbnail placeholder image',
    }
}

</script>
