// nuxt-app/pages/components/textarea.vue
<template>
  <div>
    <h3>Default</h3>
    <pie-textarea value="foo"></pie-textarea>
    <pie-divider></pie-divider>
    <h3>Resize: manual</h3>
    <pie-textarea resize="manual" value="foo"></pie-textarea>
    <pie-divider></pie-divider>
    <h3>Maxlength: 4</h3>
    <pie-textarea value="foo" maxlength="4"></pie-textarea>
  </div>
</template>

<script setup lang="ts">
import { definePageMeta } from '#imports';
import '@justeattakeaway/pie-webc/components/textarea.js';
import '@justeattakeaway/pie-webc/components/divider.js';

definePageMeta({
  title: 'Textarea',
});
</script>

// nextjs-app-v15/src/app/components/textarea/textarea.tsx
'use client';

import NavigationLayout from "@/app/layout/navigation";
import { PieTextarea } from '@justeattakeaway/pie-webc/react/textarea.js';
import { PieDivider } from '@justeattakeaway/pie-webc/react/divider.js';

export default function Textarea() {

    return (
        <NavigationLayout title="Textarea">
            <h3>Default</h3>
            <PieTextarea value="foo"/>

            <PieDivider />

            <h3>Resize: manual</h3>
            <PieTextarea
                value="foo"
                resize="manual"
            />

            <PieDivider />

            <h3>Maxlength: 4</h3>
            <PieTextarea
                value="foo"
                maxlength={4}
            />
        </NavigationLayout>
    );
}
