// nuxt-app/pages/components/tooltip.vue
<template>
    <div class="tooltip-showcase">
        <h2 class="u-font-heading-xl">Tooltip examples</h2>
        <section class="tooltip-default">
            <h3 class="u-font-heading-l">Default</h3>
            <pie-button id="default-tooltip-trigger">Delivery times</pie-button>
            <pie-tooltip trigger="default-tooltip-trigger" :isOpen="true">
                <span slot="content">Arrives today.</span>
            </pie-tooltip>
        </section>

        <section>
            <h3 class="u-font-heading-l">Dismissible</h3>
            <pie-button id="dismissible-tooltip-trigger" @click="isDismissibleOpen = true">Delivery times</pie-button>
            <pie-tooltip
                trigger="dismissible-tooltip-trigger"
                :isOpen="isDismissibleOpen"
                isDismissible
                heading="Delivery times"
                :aria="{ close: 'Close' }"
                @pie-tooltip-close="isDismissibleOpen = false">
                <span slot="content">Orders placed before 6pm arrive today.</span>
            </pie-tooltip>
        </section>

        <section>
            <h3 class="u-font-heading-l">With action</h3>
            <pie-button id="action-tooltip-trigger">Delivery times</pie-button>
            <pie-tooltip trigger="action-tooltip-trigger" :isOpen="true" heading="Delivery times">
                <span slot="content">Orders placed before 6pm arrive today.</span>
                <pie-button slot="action" size="xsmall">Next</pie-button>
            </pie-tooltip>
        </section>

        <section class="tooltip-sizing-variants">
            <h3 class="u-font-heading-l">Sizing and variants</h3>
            <pie-button id="fit-tooltip-trigger">Fit to content</pie-button>
            <pie-tooltip trigger="fit-tooltip-trigger" :isOpen="true" size="fit-to-content">
                <span slot="content">Arrives today.</span>
            </pie-tooltip>
            <div style="margin-top: var(--dt-spacing-j);">
                <pie-button id="fill-tooltip-trigger" isFullWidth style="margin-top: 150px;">Fill container</pie-button>
                <pie-tooltip trigger="fill-tooltip-trigger" :isOpen="true" size="fill-container">
                    <span slot="content">Orders placed before 6pm arrive today. Orders placed after 6pm arrive the next working day.</span>
                </pie-tooltip>
            </div>
            <div class="tooltip-inverse">
                <pie-button id="inverse-tooltip-trigger" variant="inverse">Inverse</pie-button>
                <pie-tooltip trigger="inverse-tooltip-trigger" :isOpen="true" variant="inverse">
                    <span slot="content">Arrives today.</span>
                </pie-tooltip>
            </div>
            <div style="margin-top: var(--dt-spacing-j);">
                <pie-icon-button id="icon-tooltip-trigger" :aria="{ label: 'Delivery times' }">
                    <icon-info-circle></icon-info-circle>
                </pie-icon-button>
                <pie-tooltip trigger="icon-tooltip-trigger" :isOpen="true" type="icon">
                    <span slot="content">Arrives today.</span>
                </pie-tooltip>
            </div>
        </section>

        <section>
            <h3 class="u-font-heading-l">Positions</h3>
            <div class="tooltip-positions">
                <div v-for="position in positions" :key="position" :style="{ gridArea: position }">
                    <button :id="`tooltip-${position}`" class="tooltip-placement-anchor" type="button" :aria-label="position"></button>
                    <pie-tooltip :trigger="`tooltip-${position}`" :isOpen="true" :position="position" size="fit-to-content">
                        <span slot="content">{{ position }}</span>
                    </pie-tooltip>
                </div>
            </div>
        </section>
    </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { definePageMeta } from '#imports';
import '@justeattakeaway/pie-webc/components/button.js';
import '@justeattakeaway/pie-webc/components/icon-button.js';
import '@justeattakeaway/pie-webc/components/tooltip.js';
import '@justeattakeaway/pie-icons-webc/dist/IconInfoCircle.js';

definePageMeta({
    title: 'Tooltip',
});

const isDismissibleOpen = ref(false);
const positions = ['top', 'top-start', 'top-end', 'bottom', 'bottom-start', 'bottom-end', 'left', 'left-start', 'left-end', 'right', 'right-start', 'right-end'];
</script>

<style scoped>
.tooltip-inverse {
    align-items: center;
    background-color: var(--dt-color-container-dark);
    display: flex;
    justify-content: center;
    margin-top: var(--dt-spacing-j);
    min-block-size: 160px;
    padding: var(--dt-spacing-e);
}

.tooltip-sizing-variants h3 {
    margin-block-end: 100px;
}

.tooltip-default h3 {
    margin-block-end: 100px;
}

.tooltip-positions {
    display: grid;
    column-gap: var(--dt-spacing-j);
    grid-template-areas:
        '. top-start top top-end .'
        'left-start . . . right-start'
        'left . . . right'
        'left-end . . . right-end'
        '. bottom-start bottom bottom-end .';
    justify-content: center;
    max-inline-size: 100%;
    padding: var(--dt-spacing-h) var(--dt-spacing-j);
    row-gap: var(--dt-spacing-e);
}

.tooltip-showcase {
    display: grid;
    gap: var(--dt-spacing-j);
    max-inline-size: 100%;
}

.tooltip-placement-anchor {
    background-color: var(--dt-color-container-default);
    block-size: 56px;
    border: 1px solid var(--dt-color-border-strong);
    border-radius: var(--dt-radius-rounded-b);
    cursor: pointer;
    inline-size: 56px;
}

@media (max-width: 599px) {
    .tooltip-showcase {
        text-align: center;
    }

    .tooltip-positions {
        column-gap: var(--dt-spacing-c);
        grid-template-areas:
            'top-start'
            'top'
            'top-end'
            'left-start'
            'left'
            'left-end'
            'right-start'
            'right'
            'right-end'
            'bottom-start'
            'bottom'
            'bottom-end';
        padding-inline: var(--dt-spacing-c);
        row-gap: var(--dt-spacing-j);
    }
}
</style>

// nextjs-app-v15/src/app/components/tooltip/tooltip.tsx
'use client';

import NavigationLayout from "@/app/layout/navigation";
import { PieButton } from '@justeattakeaway/pie-webc/react/button.js';
import { PieIconButton } from '@justeattakeaway/pie-webc/react/icon-button.js';
import { PieTooltip } from '@justeattakeaway/pie-webc/react/tooltip.js';
import { IconInfoCircle } from '@justeattakeaway/pie-icons-webc/dist/react/IconInfoCircle.js';
import { useState } from 'react';

const positions = ['top', 'top-start', 'top-end', 'bottom', 'bottom-start', 'bottom-end', 'left', 'left-start', 'left-end', 'right', 'right-start', 'right-end'] as const;

export default function Tooltip() {
    const [isDismissibleOpen, setIsDismissibleOpen] = useState(false);

    return (
        <NavigationLayout title="Tooltip">
            <div className="tooltip-showcase">
            <h2 className="u-font-heading-xl">Tooltip examples</h2>
            <section className="tooltip-default">
                <h3 className="u-font-heading-l">Default</h3>
                <PieButton id="default-tooltip-trigger">Delivery times</PieButton>
                <PieTooltip trigger="default-tooltip-trigger" isOpen>
                    <span slot="content">Arrives today.</span>
                </PieTooltip>
            </section>

            <section>
                <h3 className="u-font-heading-l">Dismissible</h3>
                <PieButton id="dismissible-tooltip-trigger" onClick={() => setIsDismissibleOpen(true)}>Delivery times</PieButton>
                <PieTooltip
                    trigger="dismissible-tooltip-trigger"
                    isOpen={isDismissibleOpen}
                    isDismissible
                    heading="Delivery times"
                    aria={{ close: 'Close' }}
                    onPieTooltipClose={() => setIsDismissibleOpen(false)}>
                    <span slot="content">Orders placed before 6pm arrive today.</span>
                </PieTooltip>
            </section>

            <section>
                <h3 className="u-font-heading-l">With action</h3>
                <PieButton id="action-tooltip-trigger">Delivery times</PieButton>
                <PieTooltip trigger="action-tooltip-trigger" isOpen heading="Delivery times">
                    <span slot="content">Orders placed before 6pm arrive today.</span>
                    <PieButton slot="action" size="xsmall">Next</PieButton>
                </PieTooltip>
            </section>

            <section className="tooltip-sizing-variants">
                <h3 className="u-font-heading-l">Sizing and variants</h3>
                <PieButton id="fit-tooltip-trigger">Fit to content</PieButton>
                <PieTooltip trigger="fit-tooltip-trigger" isOpen size="fit-to-content">
                    <span slot="content">Arrives today.</span>
                </PieTooltip>
                <div style={{ marginTop: 'var(--dt-spacing-j)' }}>
                    <PieButton id="fill-tooltip-trigger" isFullWidth style={{ marginTop: '150px' }}>Fill container</PieButton>
                    <PieTooltip trigger="fill-tooltip-trigger" isOpen size="fill-container">
                        <span slot="content">Orders placed before 6pm arrive today. Orders placed after 6pm arrive the next working day.</span>
                    </PieTooltip>
                </div>
                <div className="tooltip-inverse">
                    <PieButton id="inverse-tooltip-trigger" variant="inverse">Inverse</PieButton>
                    <PieTooltip trigger="inverse-tooltip-trigger" isOpen variant="inverse">
                        <span slot="content">Arrives today.</span>
                    </PieTooltip>
                </div>
                <div style={{ marginTop: 'var(--dt-spacing-j)' }}>
                    <PieIconButton id="icon-tooltip-trigger" aria={{ label: 'Delivery times' }}>
                        <IconInfoCircle />
                    </PieIconButton>
                    <PieTooltip trigger="icon-tooltip-trigger" isOpen type="icon">
                        <span slot="content">Arrives today.</span>
                    </PieTooltip>
                </div>
            </section>

            <section>
                <h3 className="u-font-heading-l">Positions</h3>
                <div className="tooltip-positions">
                    {positions.map((position) => (
                        <div key={position} style={{ gridArea: position }}>
                            <button
                                id={`tooltip-${position}`}
                                type="button"
                                aria-label={position}
                                style={{
                                    backgroundColor: 'var(--dt-color-container-default)',
                                    border: '1px solid var(--dt-color-border-strong)',
                                    borderRadius: 'var(--dt-radius-rounded-b)',
                                    blockSize: '56px',
                                    cursor: 'pointer',
                                    inlineSize: '56px',
                                }} />
                            <PieTooltip trigger={`tooltip-${position}`} isOpen position={position} size="fit-to-content">
                                <span slot="content">{position}</span>
                            </PieTooltip>
                        </div>
                    ))}
                </div>
            </section>
            </div>
            <style jsx>{`
                .tooltip-showcase {
                    display: grid;
                    gap: var(--dt-spacing-j);
                    max-inline-size: 100%;
                }

                .tooltip-sizing-variants h3 {
                    margin-block-end: 100px;
                }

                .tooltip-default h3 {
                    margin-block-end: 100px;
                }

                .tooltip-inverse {
                    align-items: center;
                    background-color: var(--dt-color-container-dark);
                    display: flex;
                    justify-content: center;
                    margin-top: var(--dt-spacing-j);
                    min-block-size: 160px;
                    padding: var(--dt-spacing-e);
                }

                .tooltip-positions {
                    display: grid;
                    row-gap: var(--dt-spacing-e);
                    column-gap: var(--dt-spacing-j);
                    grid-template-areas:
                        '. top-start top top-end .'
                        'left-start . . . right-start'
                        'left . . . right'
                        'left-end . . . right-end'
                        '. bottom-start bottom bottom-end .';
                    justify-content: center;
                    max-inline-size: 100%;
                    padding: var(--dt-spacing-h) var(--dt-spacing-j);
                }

                @media (max-width: 599px) {
                    .tooltip-showcase {
                        text-align: center;
                    }

                    .tooltip-positions {
                        column-gap: var(--dt-spacing-c);
                        grid-template-areas:
                            'top-start'
                            'top'
                            'top-end'
                            'left-start'
                            'left'
                            'left-end'
                            'right-start'
                            'right'
                            'right-end'
                            'bottom-start'
                            'bottom'
                            'bottom-end';
                        padding-inline: var(--dt-spacing-c);
                        row-gap: var(--dt-spacing-j);
                    }
                }
            `}</style>
        </NavigationLayout>
    );
}
