// nuxt-app/pages/form.vue
<template>
    <div>
        <h1>Nuxt - PIE Form Test Page</h1>
        <form class="form" id="testForm" @submit="handleSubmit">
            <pie-form-label for="username">
                Username:
            </pie-form-label>
            <pie-input
                :value="username"
                @input="handleUsernameInput"
                class="form-field"
                id="username"
                data-test-id="username"
                name="username"
                type="text"></pie-input>
        
            <label for="email">
                Email:
            </label>
            <input
                class="form-field"
                id="email"
                data-test-id="email"
                name="email"
                v-model="email"
                type="email" />
            
            <label for="password">
                Password:
            </label>
            <input
                class="form-field"
                id="password"
                data-test-id="password"
                name="password"
                v-model="password"
                type="password" />
        
            <label for="passwordConfirmation">
                Confirm Password:
            </label>
            <input
                class="form-field"
                id="passwordConfirmation"
                data-test-id="passwordConfirmation"
                name="passwordConfirmation"
                v-model="passwordConfirmation"
                type="password" />
        
            <div class="form-controls">
                <pie-form-label for="approveSettings">
                    Approve settings
                </pie-form-label>
                <pie-switch
                    id="approveSettings"
                    data-test-id="approveSettings"
                    name="approveSettings"
                    @change="handleApproveSettingsChange"
                    :checked="approveSettings"></pie-switch>
                <pie-switch
                    label="Enable Notifications"
                    id="notifications"
                    data-test-id="enableNotifications"
                    name="notifications"
                    @change="handleNotificationsChange"
                    :checked="notifications"></pie-switch>
            </div>
            <div class="form-btns">
                <pie-button class="form-btn" data-test-id="reset-btn" variant="secondary" type="reset">Reset</pie-button>
                <pie-button class="form-btn" data-test-id="submit-btn" type="submit">Submit</pie-button>
            </div>
        </form>
        <div id="output" data-test-id="output">
            <h2>Form Data</h2>
            <pre data-test-id="outputData">
                {{ formDataDisplay }}
            </pre>
        </div>
    </div>
</template>

<script setup lang="ts">
import { PieButton } from '@justeattakeaway/pie-button';
import { PieFormLabel } from '@justeattakeaway/pie-form-label';
import { PieInput } from '@justeattakeaway/pie-input';
import { PieSwitch } from '@justeattakeaway/pie-switch';
import { defineModel } from 'vue';

const username = defineModel('username', { default: '' });
const email = defineModel('email', { default: '' });
const password = defineModel('password', { default: '' });
const passwordConfirmation = defineModel('passwordConfirmation', { default: '' });
const approveSettings = defineModel('approveSettings', { default: false });
const notifications = defineModel('notifications', { default: false });

const formDataDisplay = defineModel('formDataDisplay');

function handleSubmit(event) {
    event.preventDefault();
    formDataDisplay.value = JSON.stringify({
        username: username.value,
        email: email.value,
        password: password.value,
        passwordConfirmation: passwordConfirmation.value,
        approveSettings: approveSettings.value,
        enableNotifications: notifications.value
    }, null, 2);
}

function handleUsernameInput(event) {
    username.value = event.target.value;
}

function handleNotificationsChange(event) {
    notifications.value = event.target.checked;
}

function handleApproveSettingsChange(event) {
    approveSettings.value = event.target.checked;
}

</script>

<style scoped>
     /* Form Styles */
    .form {
        display: flex;
        flex-direction: column;
    }

    .form-field {
        margin-bottom: var(--dt-spacing-b);
    }

    .form-controls {
        margin-top: var(--dt-spacing-e);
        > * {
            display: block;
        }

        > * + * {
            margin-top: var(--dt-spacing-b);
        }
    }

    .form-btns {
        margin-top: var(--dt-spacing-c);
        display: flex;
        gap: var(--dt-spacing-a)
    }

    .form-btns > .form-btn:first-of-type {
        margin-left: auto;
    }
</style>

// nextjs-app/src/pages/form.tsx
import React, { useState } from 'react';
import { PieFormLabel } from '@justeattakeaway/pie-form-label/dist/react';
import { PieSwitch } from '@justeattakeaway/pie-switch/dist/react';
import { PieButton } from '@justeattakeaway/pie-button/dist/react';
import { PieInput } from '@justeattakeaway/pie-input/dist/react';

export default function Form() {
    const [approveSettings, setApproveSettings] = useState(false);
    const [enableNotifications, setNotifications] = useState(false);
    const [formDataDisplay, setFormDataDisplay] = useState<string | null>(null);

    const [username, setUsername] = useState('');
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [passwordConfirmation, setPasswordConfirmation] = useState('');

    const handleUsernameInput = (event: InputEvent) => {
        setUsername((event.target as HTMLInputElement).value);
    }

    const handleEmailChange = (event: React.ChangeEvent<HTMLInputElement>) => {
        setEmail(event.target.value);   
    }

    const handlePasswordChange = (event: React.ChangeEvent<HTMLInputElement>) => {
        setPassword(event.target.value);   
    }

    const handlePasswordConfirmationChange = (event: React.ChangeEvent<HTMLInputElement>) => {
        setPasswordConfirmation(event.target.value);   
    }

    const handleApproveSettingsChange = () => {
        setApproveSettings(current => !current);
    };

    const handleNotificationsChange = () => {
        setNotifications(current => !current);
    };

    const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
        event.preventDefault();
        const data = { 
            approveSettings,
            enableNotifications,
            username, 
            email, 
            password, 
            passwordConfirmation
        };
        
        setFormDataDisplay(JSON.stringify(data, null, 2));
    };

    return (
        <>
            <h1>NextJS - PIE Form Test Page</h1>
            <form className="form" id="testForm" onSubmit={handleSubmit}>
                <PieFormLabel for="username">
                    Username:
                </PieFormLabel>
                <PieInput
                    className="form-field"
                    id="username"
                    data-test-id="username"
                    name="username"
                    value={username}
                    onInput={handleUsernameInput as any}
                    type="text"></PieInput>

                <label htmlFor="email">
                    Email:
                </label>
                <input
                    className="form-field"
                    id="email"
                    data-test-id="email"
                    name="email"
                    onChange={handleEmailChange}
                    type="email" />
                
                <label htmlFor="password">
                    Password:
                </label>
                <input
                    className="form-field"
                    id="password"
                    data-test-id="password"
                    name="password"
                    onChange={handlePasswordChange}
                    type="password" />

                <label htmlFor="passwordConfirmation">
                    Confirm Password:
                </label>
                <input
                    className="form-field"
                    id="passwordConfirmation"
                    data-test-id="passwordConfirmation"
                    name="passwordConfirmation"
                    onChange={handlePasswordConfirmationChange}
                    type="password" />

                <div className="form-controls">
                    <PieFormLabel for="approveSettings">
                        Approve settings
                    </PieFormLabel>
                    <PieSwitch
                        id="approveSettings"
                        data-test-id="approveSettings"
                        name="approveSettings"
                        checked={approveSettings}
                        onChange={handleApproveSettingsChange}
                    />
                    <PieSwitch
                        label="Enable Notifications"
                        id="enableNotifications"
                        data-test-id="enableNotifications"
                        name="enableNotifications"
                        checked={enableNotifications}
                        onChange={handleNotificationsChange}
                    />
                </div>
                <div className='form-btns'>
                    <PieButton className="form-btn" data-test-id="reset-btn" variant="secondary" type="reset">Reset</PieButton>
                    <PieButton className="form-btn" data-test-id="submit-btn" type="submit">Submit</PieButton>
                </div>
            </form>
            {formDataDisplay && (
                <div id="output">
                    <h2>Form Data</h2>
                    <pre data-test-id="outputData">{formDataDisplay}</pre>
                </div>
            )}
        </>
    );
}
