// nuxt-app/pages/components/radio.vue
<template>
    <div>
      <pie-radio :checked="checked" value="value" @change="handleRadioChange">
        {{ `checked: ${checked}` }}
      </pie-radio>
    </div>
  </template>

  <script setup lang="ts">
  import { ref } from 'vue';
  import { definePageMeta } from '#imports';
  import '@justeattakeaway/pie-webc/components/radio.js';

  definePageMeta({
      title: 'Radio',
  });

  let checked = ref(false);

  function handleRadioChange() {
    checked.value = !checked.value;
  }

  </script>

// nextjs-app-v14/src/app/components/radio/radio.tsx
'use client';

import NavigationLayout from "@/app/layout/navigation";
import { PieRadio } from "@justeattakeaway/pie-webc/react/radio.js";
import { useState } from "react";

export default function Radio() {
    const [isRadioChecked, setIsRadioCheck] = useState(false);

    const handleRadioInput = () => {
        setIsRadioCheck(current => !current);
    };

    return (
        <NavigationLayout title="Radio">
            <PieRadio
                checked={isRadioChecked}
                value="value"
                onInput={handleRadioInput}>
                {`checked: ${isRadioChecked}`}
            </PieRadio>
        </NavigationLayout>
    );
}
