// nuxt-app/pages/components/assistive-text.vue
<template>
	<div>
		<pie-assistive-text variant="default">Assistive Text Default</pie-assistive-text>
		<pie-assistive-text variant="success">Assistive Text Success</pie-assistive-text>
		<pie-assistive-text variant="error">Assistive Text Error</pie-assistive-text>
	</div>
</template>

<script setup lang="ts">
import { definePageMeta } from '#imports';
import '@justeattakeaway/pie-webc/components/assistive-text.js';

definePageMeta({
    title: 'Assistive Text',
});
</script>

// nextjs-app-v14/src/app/components/assistive-text/page.tsx
'use client';

import NavigationLayout from "@/layout/navigation";
import { PieAssistiveText } from '@justeattakeaway/pie-webc/react/assistive-text.js';

export default function AssistiveText() {
    return (
        <NavigationLayout title="Assistive Text">
        <PieAssistiveText>Assistive Text</PieAssistiveText>
        <PieAssistiveText variant="success">Assistive Text</PieAssistiveText>
        <PieAssistiveText variant="error">Assistive Text</PieAssistiveText>
        </NavigationLayout>
    );
}
