// nuxt-app/pages/components/avatar.vue
<template>
	<div>
	<h1>Avatar Static Initials</h1>
		<pie-avatar label="Ada Lovelace" tag="div"></pie-avatar>
	<h1> Avatar Fallback </h1>
		<pie-avatar tag="div"></pie-avatar>
	</div>
</template>

<script setup lang="ts">
import { definePageMeta } from '#imports';
import '@justeattakeaway/pie-webc/components/avatar.js';
definePageMeta({
    title: 'PIE Avatar',
});
</script>

// nextjs-app-v15/src/app/components/avatar/avatar.tsx
'use client';

import NavigationLayout from "@/app/layout/navigation";
import { PieAvatar } from '@justeattakeaway/pie-webc/react/avatar.js';

export default function Avatar() {
    return (
        <NavigationLayout title="Avatar">
            <h1>Avatar Static Initials</h1>
            <PieAvatar label="Ada Lovelace" tag="div"></PieAvatar>
            <h1>Avatar Fallback</h1>
            <PieAvatar tag="div"></PieAvatar>
        </NavigationLayout>
    );
}
