// nuxt-app/pages/components/modal.vue
<template>
  <div>
    <pie-button @click="openModal">Open Modal</pie-button>
    <pie-modal
        v-if="open"
        heading="Modal Header"
        hasBackButton
        isDismissible
        :leadingAction="leadingAction"
        :isOpen="open"
        @pie-modal-close="handleModalClose"
        @pie-modal-back="handleModalClose"
    >
      <p>Modal content</p>
    </pie-modal>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { definePageMeta } from '#imports';
import '@justeattakeaway/pie-webc/components/button.js';
import '@justeattakeaway/pie-webc/components/modal.js';

definePageMeta({
    title: 'PIE Modal',
});

let open = ref(false);

onMounted(() => {
  openModal();
});

function openModal() {
  open.value = true;
}

function handleModalClose() {
  open.value = false;
}

const leadingAction = {
  text: 'Leading action',
};

</script>

// nextjs-app-v14/src/app/components/modal/modal.tsx
'use client';

import NavigationLayout from "@/app/layout/navigation";
import { PieButton } from '@justeattakeaway/pie-webc/react/button.js';
import { PieModal } from '@justeattakeaway/pie-webc/react/modal.js';
import { useState } from "react";

export default function Modal() {
    const [isModalOpen, setIsModalOpen] = useState(true);

    return (
        <NavigationLayout title="Modal">
        <PieButton onClick={() => setIsModalOpen(true)}>Open Modal</PieButton>
        <PieModal
            isOpen={isModalOpen}
            heading="Modal Header"
            isDismissible
            hasBackButton
            leadingAction={{
                text: 'Leading action',
            }}
            onPieModalClose={() => setIsModalOpen(false)}
            onPieModalBack={() => setIsModalOpen(false)}
        >
            <p>Modal content</p>
        </PieModal>
        </NavigationLayout>
    );
}
